src-tauri/src/cpu_miner.rs, src-tauri/src/process_watcher.rs
Description
---
Shutdown signal is not always recreated after restart. It leads to the instant process shut down.
---
---
---
---
=> fix(mining): can't stop and restart mining

src-tauri/Cargo.lock, src-tauri/Cargo.toml
Description
Build xz2 static bind
Reduce the need for brew installs for OSX
Built and run in local VM
---
---
=> ci(fix): osx lzma bind static

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/binary_resolver.rs, src-tauri/src/cpu_miner.rs, src-tauri/src/download_utils.rs, src-tauri/src/main.rs, src-tauri/src/merge_mining_adapter.rs, src-tauri/src/minotari_node_adapter.rs, src-tauri/src/mm_proxy_manager.rs, src-tauri/src/node_manager.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_watcher.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs, src-tauri/src/xmrig_adapter.rs, src/App.tsx
=> feat: add better download and sync status reporting

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src/containers/SideBar/components/Settings.tsx, src/hooks/useGetSeedWords.ts, src/utils/truncateString.ts
Description
---
Originally posted in #38 
Co-authored-by: @mmrrnn
=> feat: show seed words

index.html, src-tauri/tauri.conf.json, src/App.tsx, src/containers/TitleBar/TitleBar.tsx
Description
---
- moved canvas styling to App.tsx to be able to access the `appBorderRadius` value 
- updated styling (removed padding to fix the ugly left side cut-off & adjusted the window sizes slightly) - still need to get a better positioned version from lusion though
---
---
- locally 
---
---
=> fix(ui): fixed visualisation overflow

package-lock.json, package.json, vite.config.ts
Description
---
- previously added rollupOptions in build config for `@emotion/react` console warning but that borked it 
- also updated vite initially thinking that was the issue (was not but no breaking changes so did not revert)
---
---
---
---
=> fix(ui): removed rollup options for build

src-tauri/src/cpu_miner.rs, src-tauri/src/merge_mining_adapter.rs, src-tauri/src/node_adapter.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_killer.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/xmrig_adapter.rs
Description
---
I'm not satisfied with xmrig_adapter refactor - I can't satisfy ProcessAdapter trait without writing useless spawn_inner method
I reused ProcessInstance across all adapters
---
---
---
---
=> chore(refactor): reuse more code in adapters

src-tauri/src/app_config.rs, src-tauri/src/binary_resolver.rs, src-tauri/src/main.rs, src/App.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/hooks/useEnvironment.ts, src/hooks/useGetApplicationsVersions.ts, src/hooks/useGetSeedWords.ts, src/store/useAppStatusStore.ts, src/types/invoke.ts
Description
---
-  Added 6h period for calling to github for newest version of application during app startup
-  Added temporary method for loading versions data from cache folder
-  Added hook for checking app Environment
-  Added button in settings for dev Environment for forcing check and download of newest versions 
---
Currently when application was started many times in short span of time it would hit rate limit for github api
---
Manually
---
---
=> feat: implement better caching for applications versions

src-tauri/src/main.rs, src/containers/SideBar/Miner/components/ModeSelect.tsx
Description
---
Mode change had no implication on the running mining process. We need to restart mining.
---
---
Manually, unfortunately I'm not able to attach screen recording since it does not work on my local along with mining
---
---
=> fix(modes): restart mining when mode changed

src/containers/Dashboard/Dashboard.tsx, src/containers/Dashboard/MiningView/components/Earnings.tsx, src/containers/Dashboard/SetupView/SetupView.tsx, src/containers/Dashboard/styles.ts, src/hooks/mining/useBalanceInfo.ts, src/hooks/mining/useVisualisation.ts, src/store/useMiningStore.ts
Description
---
- added gradient opacity bg to setup screen so you can read the status better
- added flag for animation completed before updating block height
---
---
---
https://github.com/user-attachments/assets/2c4739d5-b7a2-4cd3-8d7f-8dc5ce447af3
---
=> fix(ui): add block height delay after animations and set up background

package-lock.json, src/containers/Dashboard/MiningView/components/BlockHeight.tsx, src/containers/Dashboard/MiningView/components/Earnings.tsx, src/hooks/mining/useBalanceInfo.ts, src/hooks/mining/useBlockInfo.ts, src/hooks/mining/useVisualisation.ts, src/store/useMiningStore.ts
Description
---
- only update `displayBlockHeight` if timer is not paused
- update `timerPaused` after success (earnings) animation callback, and with a small timeout on a failed block animation (success and fail animations have differing durations)
- changed display block time init value to `-1` so the counter starts at `00:00:00` instead of `00:00:01`
- also just used actual block_height value if not mining, so we're up to date even if there's no animation changes
---
- display block height was changing before the display block time
---
- locally
https://github.com/user-attachments/assets/a3050a2b-812e-44fc-945b-58a320c66345
https://github.com/user-attachments/assets/47feaba7-acfb-4f52-89e3-6e72d50c0f73
=> fix(ui): sync display height and time timing

src/components/CharSpinner/CharSpinner.styles.ts, src/containers/Dashboard/MiningView/components/Earnings.styles.ts, src/containers/Dashboard/MiningView/components/Earnings.tsx, src/containers/SideBar/components/Wallet.tsx, src/hooks/mining/useBalanceInfo.ts
Description
---
- fix `m` unit being cut off in wallet balance
- fix earnings animation text ugliness if window is smaller
- increased timeout to wait for balance change to 15 seconds
- reset earnings on `setDisplayBlockHeight` change so we don't get an old earnings animation on a failed block when we return
=> fix(ui): success animation after minimising & unit cut off

src/containers/Dashboard/MiningView/components/BlockHeight.tsx, src/containers/Dashboard/MiningView/components/BlockTime.styles.ts
Description
---
Adjusted the timer z-index
Conditionally render the block height component only if the height is bigger than 0
---
The block height background was overlapping the timer at the bottom of the screen
---
Manually
---
---
x
=> fix(ui): block height display

src/containers/AppBackground/AppBackground.tsx, src/containers/Dashboard/Dashboard.tsx, src/containers/Dashboard/styles.ts
Description
---
- just added a flag for 'setup' view in `AppBackground`
- remove `SetupGradient`
---
- resolves #136
=> fix(ui): remove Setup view gradient bg and just use AppBackground on set up

src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src/containers/Dashboard/MiningView/components/MiningButton.tsx, src/containers/SideBar/Miner/Miner.tsx, src/containers/SideBar/Miner/components/AutoMiner/AutoMiner.tsx, src/hooks/mining/useMiningControls.ts, src/hooks/useGetStatus.ts, src/store/useCPUStatusStore.ts, src/store/useUIStore.ts, src/types/app-status.ts, src/visuals.ts
Description
---
Improve mining states transitions 
---
Currently sometimes mining button went into disable state when it should not and handling state for lost internet connection was missing
---
Manually
---
Play with mining, disable internet connection during mining 
---
=> feat: mining button state adjustments

src-tauri/src/binary_resolver.rs
Checks if a file actually exists when checking versions. 
We had a user who had an in_progress dir for a version:
This would cause a crash on startup
=> fix: check file physically exists when looking for versions

eslint.config.js, package-lock.json, package.json
Description
---
Adds linting configuration used by airbnb
---
There was inconsistent file formating
---
- Check your edditor formatter
- Run `npm run lint:fix` before running a PR
---
I haven't run the linter on this PR in case there is work in progress from @shanimal08 and or @NovaT82 in order to avoid introducing conflicts
---
=> feat: adds stylisitc

src/containers/Dashboard/SetupView/SetupView.tsx, src/containers/Dashboard/SetupView/styles.ts
Description
---
Added a nice "floating" animation to the Meditating Soon character on the initial setup screen. 
Video of the animation: 
https://www.loom.com/share/d7c4f7bfbadf480abdae47f73f027b78?sid=27890e94-314e-416d-842d-410b1c480648
---
Just adding a little personality
---
Running on local Dev, Mac M1 Pro
---
1. On the initial setup screen when the app first loads, the SOON character should be floating up and down. 
---
=> feat(ui): floating animation for character on setup screen

.github/workflows/release.yml
Description
Resolve OSX universal builds by installing all rust components for both arch from the src-tauri folder
Enabled linux builds
Fix OSX builds
Add Linux builds
Builds in local fork
=> ci(fix): resolve osx universal builds, enable linux builds

index.html, public/locales/en/common.json, src-tauri/tauri.conf.json, src/components/elements/Chip.tsx, src/containers/SideBar/components/Heading.tsx
Description
---
- added basic chip component
- added chip with 'Testnet' to sidebar title
- added 'Testnet' to config window and app name
---
- resolves #92 
---
- locally:
=> feat(ui): add chip component and Testnet tag

index.html, src-tauri/tauri.conf.json, src/components/elements/Select.tsx, src/containers/Dashboard/MiningView/MiningView.styles.ts, src/containers/Dashboard/MiningView/MiningView.tsx, src/containers/Dashboard/MiningView/components/BlockHeight.styles.ts, src/containers/Dashboard/MiningView/components/BlockHeight.tsx, src/containers/Dashboard/MiningView/components/Earnings.styles.ts, src/containers/SideBar/Miner/Miner.tsx, src/hooks/helpers/useWindowSize.ts, src/hooks/useGetStatus.ts
Description
---
- adjusted visual camera offset slightly
- added minimum window size
- adjusted `BlockHeight` component structure and styling so it's always vertically centered
- use `height` value which for the render check since displayBlockHeight might not always be set (which is why it sometimes wouldn't show initially)
- adjusted `BlockHeight` component's big height accent number to scale based on number length as well as window height
- added basic screensize helper hook 
- updated media query below new min screen size and some lints
---
- broke the font-size scaling of the big block height accent in a previous PR
- some times the ruler and centered block-height would overlap the block tower
---
- locally:
---
---
---
---
---
---
=> fix(ui): block height bg scaling

src/hooks/mining/useVisualisation.ts
only clear the animation pause & post-block animation flag if it was the `'fail'` state in `useVisualisation` (gets cleared for `'success'`in earnings after the fancy floating animation which takes longer)
=> fix: success animation timing

src/components/elements/Chip.tsx, src/components/elements/inputs/Select.styles.ts, src/containers/SideBar/Miner/Miner.tsx, src/containers/SideBar/Miner/components/ExpandableTile.styles.ts, src/containers/SideBar/Miner/components/ExpandableTile.tsx, src/containers/SideBar/Miner/styles.ts
Description
---
- fix small chip vertical alignment
- remove last child expanded styling and set all stats cards the same with
- remove chip name state card
- use tooltip/popover for estimated earnings instead of just expanding it
- add `-` for stat value if not mining or cpu/gpu mining not enabled
---
- used wrong section from designs - updated per standup
---
- locally 
https://github.com/user-attachments/assets/de94c6c0-e9db-42ba-8abd-8deef43ea7a8
https://github.com/user-attachments/assets/7867cf03-786b-4adf-bdc3-17dc46b865b2
=> fix(ui): fix stats

public/locales/af/setup-view.json, public/locales/en/setup-view.json, public/locales/pl/setup-view.json, src-tauri/src/main.rs, src-tauri/src/wallet_adapter.rs, src-tauri/tauri.conf.json, src/App.tsx, src/containers/AutoUpdateDialog/AutoUpdateDialog.styles.ts, src/containers/AutoUpdateDialog/AutoUpdateDialog.tsx, src/hooks/useSetUp.ts, src/store/appStateStore.ts
Description
---
Currently auto update asks you to 1) Download and then 2) Restart. It was a request to merge it into one(first) step. 
---
Unfortunately, tauri updater does not allow to do so and it does not show that second step on windows. I tried to catch "DOWNLOADED" and "DONE" events, but it took some time to restart the app so restart dialog was displayed on linux/mac anyway. I decided to create our own dialog with auto update and restart logic.
---
Manually
---
if you're using linux, it's quite challenging for now. You have to build your own (old)version, create updater json, host it somewhere and place it inside `tauri.conf.json`. Ask me for help if you need any! :) …
=> chore(update): custom auto update

src-tauri/src/main.rs, src-tauri/src/mm_proxy_adapter.rs, src-tauri/src/mm_proxy_manager.rs
Description
---
When p2pool is enabled in config, merge-mining proxy was initialized with p2pool as not enabled by default.
The actual p2pool config must be passed even when its startup.
---
Initially CPU mining was not used p2pool even when it was enabled.
---
Start Universe and start mining.
Check logs that new blocks are submitted to p2pool from cpu miner as well.
---
See tests.
---
=> fix: startup config for mm proxy when p2pool enabled

src/containers/SideBar/components/Wallet.styles.ts, src/containers/SideBar/components/Wallet.tsx
Description
Fix color and position of Wallet Balance text
Resolves #304 
Before:
After:
Manually
---
=> fix(ui): wallet balance text

src/hooks/mining/useBalanceChanges.ts
Description
---
previously changed the balanceRef check (to check for 0) so it wouldn't show success/earnings when changing from 0 to balance, but that broke the flow since it never registered any changes in balance because the initial value was 0, and ref was only updated after balance change, so fixed the logic: 
- removed check for 0 on the ref from `balanceHasChanges`
- changed `hasEarnings` to just check that balance isn't 0, but diff != balance (fixes original issue
=> fix: balance check for success animation

src/containers/SideBar/components/Settings/Markups/P2pMarkup.tsx, src/containers/SideBar/components/Settings/Markups/P2poolStatsMarkup.tsx, src/containers/SideBar/components/Settings/Settings.tsx
Description
---
In experimental tab in settings modal, p2pool enabled/disabled checkbox was duplicated, it was fixed and added p2pool stats when p2pool is enabled in experimental tab.
---
---
- Start Universe
- Check settings
---
---
=> fix: fix duplicated p2pool enabled checkbox and added p2pool stats

public/locales/en/settings.json, src/containers/SideBar/components/Settings/ExperimentalWarning.tsx, src/containers/SideBar/components/Settings/Markups/SeedWordsMarkup/SeedWords.tsx, src/containers/SideBar/components/Settings/Markups/SeedWordsMarkup/SeedWordsMarkup.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/store/useUIStore.ts
Description
---
Add a switch to show or hide experimental settings
Updated the layout of seed words
---
Users were using the experimental settings that are still under development and experiencing bugs
---
Manually
---
Go to settings / experimental and switch them on or off
---
x
=> feat(ui): experimental settings switch

src/containers/SideBar/Miner/components/ButtonOrbitAnimation.tsx, src/hooks/mining/useMiningUiStateMachine.ts
- use a ref to check the initial `handleStart` since auto-mining and cpu/gpu mining flags may not be ready yet when that initially runs (so we need the dependencies there)
- also moved `window?.glApp?.stateManager.statusIndex` into an external var so the value would make a difference to the dep array
- tiny tweak to the orbit animation initial delay
---
https://github.com/user-attachments/assets/4cf9a309-1ccc-4337-b376-39a8375893e5
=> fix: update deps and init start logic

src-tauri/src/p2pool_adapter.rs
Description
---
Now when p2pool is about to start, it will only last 5 seconds maximum to try to find squads instead of the previous 30 seconds. This decreases startup time of p2pool in universe.
=> fix(p2pool): set timeout for p2pool list-tribes command

public/locales/af/common.json, public/locales/cn/common.json, public/locales/en/common.json, public/locales/pl/common.json, public/locales/tr/common.json, src-tauri/src/binary_resolver.rs, src-tauri/src/main.rs, src-tauri/src/node_manager.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/xmrig_adapter.rs, src/App.tsx, src/containers/CriticalErrorDialog/CriticalErrorDialog.tsx, src/hooks/useSetUp.ts, src/store/appStateStore.ts, src/types/invoke.ts
* Added `CriticalErrorDialog` for critical errors that affect the app so we have to force the exit
* Increased reliability of `setup_application`  - filtered unimportant errors so they won't be treated as critical errors
* Create common `stop_all_miners` method and use it for `tauri::RunEvent::ExitRequested`, `tauri::RunEvent::Exit` events and `reset_settings` , `exit_application` methods
* Moved xmrig binaries to the binaries directory to unify with all rest
* Small improvements: removed unused properties from appStateStore - setErrorOpen and errorOpen | implemented clone method for `P2poolManager`
=> fix(setup): critical errors when setup application

public/locales/en/airdrop.json, src/containers/Airdrop/AirdropGiftTracker/components/Gems/Gems.tsx, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/LoggedIn.tsx, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Invite/Invite.tsx, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Invite/styles.ts
Bug:
Fixed:
Also added rounding to the gems number to remove decimals.
=> fix(ui): fixed bonus text spacing issue

public/locales/af/mining-view.json, public/locales/cn/mining-view.json, public/locales/en/mining-view.json, public/locales/en/settings.json, public/locales/pl/mining-view.json, public/locales/tr/mining-view.json, src/components/CharSpinner/CharSpinner.styles.ts, src/containers/Dashboard/MiningView/components/MiningButton.tsx, src/containers/SideBar/Miner/components/ButtonOrbitAnimation.styles.ts, src/containers/SideBar/Miner/components/ButtonOrbitAnimation.tsx
Description
---
- updated mining button copy: `Pause Mining` => `Stop Mining` (please check translations)
- updated `send-logs` copy `Send logs` => `Submit an Issue & Logs`
- adjusted `CharSpinner` styling to handle kerning a bit better - tighter letter spacing to match designs, but also caters for the decimal and unit character
- adjust mining button Orbit animation:
- brought opacities down (on tracks and cubes)
- used less `dashed` and more `solid` borders on the track
- brought the speed down a lot (duration up)
- less blocks allowed per track
---
resolves:
- #460 
- #595 & #558 
- #594 
---
https://github.com/user-attachments/assets/f492b62a-bec6-4c43-9c7a-05bb246acdc4
=> fix(ui): wallet spacing | copy update | button ani update

.github/workflows/release.yml, src-tauri/src/binaries/adapter_github.rs, src-tauri/src/binaries/adapter_xmrig.rs, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src-tauri/tauri.conf.json
Stores data in `<data>/com.tari.universe.beta` instead of `com.tari.universe` for development and beta builds, allowing developers to run both without confusion. 
Seed words are also stored in a different keychain location for beta and release.
Note: requires release builds to be built with `feature = "release-ci"`
=> fix: allow beta builds on same computer as main builds

src/containers/Dashboard/MiningView/components/MiningButton.styles.ts
Description
---
- just made the disabled opacity change more obvious and added the 'wait' cursor
---
- resolves #672 
---
- locally:
https://github.com/user-attachments/assets/cd101029-b8dd-430a-ae3a-47759cf20a7a
https://github.com/user-attachments/assets/a99be3ae-b54b-42b3-91b3-ac6a11dc5224
=> fix(ui): mining button | more obvious diabled state

src/containers/SideBar/components/Wallet.tsx, src/store/useBlockchainVisualisationStore.ts, src/store/useWalletStore.ts
Description
---
- set balance initial state to `null` and check specifically for `null` instead of `0` to display the `-`
---
- misunderstood the requirement for #633 and set it to always be `-` if 0
NOTE: 
- this undoes the initial fix for #633 since the BE returns 0 while it's loading anyway so the `-` hardly has time to show 😅
=> fix: wallet balance display if no tXTM

.github/workflows/release.yml, package-lock.json, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json
Description
Add local defulat builds as alpha, ci for beta and release
Give users that fork the repo and build local an build labeled alpha
Ci none release builds as beta ... found that we can use [], nor ## nor dashes
Builds locally and in local fork with CI and uploads assets as expected for all OS (Windows/OSX/Linux)
=> chore(ci): add local builds as alpha, ci for beta and release

index.html, src/store/useWalletStore.ts
Description
---
- changed canvas BG gradient colour to better suit designs
- only update wallet balance in stoore if there is a value from BE (not default to 0)
---
- resolves #687 
- fixes #671 properly after BE update
---
locally: 
https://github.com/user-attachments/assets/013e3e41-13cf-483f-b7d2-1ef8852ad1a6
=> fix(ui): canvas BG and initial wallet

src/components/elements/CircularProgress.tsx
Description
---
- fixed `CircularProgress` wrapper styling
---
noticed a previous change to `CircularProgress` borked the shut down screen
| before ☹️ | after ✨  |
| :---: | :---: |
| <img width="1412" alt="image" src="https://github.com/user-attachments/assets/6284eb65-3113-4907-bafa-41fa79d27d1d"> | <img width="1478" alt="image" src="https://github.com/user-attachments/assets/687a5630-8248-4948-85f9-4a8c70e14514"> |
also centering in buttons, etc. is still fine:
=> fix(ui): circular progress wrapper

.github/workflows/ci.yml
Description
---
After release of stable tauri 2.0 the new default version for tauri-cli is 2.0 which brakes build on CI.
---
Fix failing builds due invalid version.
---
Force CI run by changing rules of triggering worklfow.
---
Check action history.
---
=> fix: lock tauri-cli version in CI

src/containers/Settings/sections/experimental/P2poolStatsMarkup.tsx
Description
---
Add default values for p2pool stats.
---
Fix `undefined` displayed in experimental setting during initialization.
---
Run app and check if there is any `undefined` in experimental settings.
---
Same as above.
---
=> fix: add default values for p2pool during initialization

src-tauri/src/main.rs, src/containers/AutoUpdateDialog/UpdatedStatus.tsx
- Limit `downloaded` value to not exceed `content_length` value
- Prevent displaying progress bar when `content_length` is zero
- Add `info!` log with `chunk_length`, `content_length` and `downloaded` values for future debugging
=> fix: handle overflowing updater numbers

src/containers/Airdrop/AirdropGiftTracker/AirdropGiftTracker.tsx, src/containers/Airdrop/AirdropGiftTracker/styles.ts, src/containers/SideBar/components/Wallet/Wallet.styles.ts, src/containers/SideBar/components/Wallet/Wallet.tsx, src/containers/SideBar/styles.ts
Description
---
- adjust wrappers so we can use `layout` prop & adjusted the expanding animation slightly
- set height on wallet balance section
- set bottom padding in bottom sidebar section to cater for the fixed wallet card so airdrop UI is above
---
- locally
https://github.com/user-attachments/assets/fbeb702b-d20c-4110-b339-81c17ac92c9c
=> fix: sidebar layout | hidden airdrop ui

src/containers/SideBar/components/Heading.tsx, src/containers/SideBar/components/VersionChip/ConnectedPulse/ConnectedPulse.tsx, src/containers/SideBar/components/VersionChip/ConnectedPulse/styles.ts, src/containers/SideBar/components/VersionChip/VersionChip.tsx, src/containers/SideBar/components/VersionChip/styles.ts
- Moved the chip in the sidebar header into it's own `VersionChip` component.
- Added a `ConnectedPulse` indicator component that shows yellow while connecting and green once connected.
- Updated version number to grey to match designs.
Question: Im using the `isSettingUp` value from `useAppStateStore` to check the status of the connection, are there other / different checks that should be made for proper integration?
=> feat(ui): added connection indicator to version chip

src/components/elements/ToggleSwitch.tsx, src/components/elements/buttons/ButtonBase.styles.ts, src/components/elements/buttons/ButtonBase.tsx, src/containers/Settings/sections/experimental/P2pMarkup.tsx, src/containers/SideBar/components/Wallet/Wallet.styles.ts, src/theme/colors.ts, src/theme/tokens.ts
Description
---
- change toggle switch disabled styling to still be green but much lighter, instead of grey
- only disable when mining is setting up, allow for it to be toggled, but prompt an app restart
---
- locally:
https://github.com/user-attachments/assets/334dce98-b574-4c2e-9c81-2f4b1e442e28
=> fix(ui): add restart modal | remove disabling

src-tauri/src/binaries/adapter_tor.rs
Description
---
Tor was missing a failsafe mirror like other binaries.
---
Tor was blocked on 0.5.9 and needed a mirror CDN.
---
On windows machine remove tor binaries and run again to check if works.
---
Same as above.
---
=> fix(binaries): add failsafe mirror to the tor binaries

src-tauri/src/process_adapter.rs
Description
---
Add additional logging if parsing pid file content fails. 
---
Some users experienced error while parsing pid file content. The issue could be localization but without any logs we can't be sure. 
---
Manually modified `node_pid`  file content to contain invalid pid number and close abnormally app to prevent graceful shutdown (app rebuild by saving changes in code editor or use tools like `xkill`).
---
Same as above.
---
=> fix: add logging if parsing pid file failed

src-tauri/src/external_dependencies.rs
randomx.rs needs 2019 and won't work with 2022 version
=> fix: limit allowed versions to only 2019

index.html, src/components/elements/inputs/Select.styles.ts, src/containers/Airdrop/AirdropGiftTracker/components/Claimmodal/styles.ts, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/LoggedIn.tsx, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Flare/styles.ts, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/UserInfo/styles.ts, src/containers/Dashboard/MiningView/components/BlockHeightAccent.styles.ts, src/containers/Dashboard/MiningView/components/BlockHeightAccent.tsx, src/containers/Dashboard/MiningView/components/BlockTime.styles.ts, src/containers/Dashboard/MiningView/components/Earnings.styles.ts, src/containers/Dashboard/MiningView/components/Ruler.tsx, src/containers/ExternalDependenciesDialog/ExternalDependenciesDialog.tsx, src/containers/ExternalDependenciesDialog/ExternalDependenciesDialog.utils.ts, src/containers/ExternalDependenciesDialog/ExternalDependencyCard.tsx, src/containers/SideBar/Miner/components/ModeSelect.tsx, src/containers/SideBar/Miner/styles.ts, src/containers/SideBar/components/Heading.tsx, src/containers/SideBar/components/VersionChip/styles.ts, src/hooks/useSetUp.ts, src/theme/GlobalStyle.ts, src/theme/fonts/druk.ts, src/theme/tokens.ts
Description
---
- update Tower Animation canvas background gradient colours
- fix global fonts:
- specify Druk _Wide_ and use narrow Druk for the gem earnings animation
- use correct font family name set in font-fae for `Poppins` in the GlobalStyles
- adjust `BlockHeightAccent`  `Ruler` styling to suit comments from the UI QA runthrough:
- adjusted sizing to it's not spread out as far to the top and bottom of the screen
- tried to mitigate the overlap on narrower screen sizes by lowering the size if the window height is high, but width lower (though this is more an issue of the tower not scaling down more in these cases, which needs to be fixed/adjusted in the webgl)
- bring down the font-size for the main ruler mark number on lower resolutions 
- format numbers
- fixed some typos and …
=> fix(ui): global font and font faces

src/components/elements/inputs/Select.styles.ts, src/components/elements/inputs/Select.tsx, src/containers/Dashboard/MiningView/components/BlockHeightAccent.styles.ts, src/containers/Dashboard/MiningView/components/BlockHeightAccent.tsx, src/containers/Dashboard/MiningView/components/Ruler.styles.ts, src/containers/Dashboard/MiningView/components/Ruler.tsx, src/containers/Settings/components/LanguageDropdown.tsx, src/containers/SideBar/Miner/components/ModeSelect.tsx, src/containers/SideBar/Miner/styles.ts, src/containers/SideBar/SideBar.tsx, src/containers/SideBar/components/Wallet/Wallet.styles.ts, src/containers/SideBar/components/Wallet/Wallet.tsx, src/containers/SideBar/styles.ts
- Adjusted padding and border radius on sidebar container
- Removed divider line between tiles and start mining button
- Adjusted spacing on mining stat tiles to make them tighter
- Adjusted large sidebar text to blend it in to the background more and moved it closer to the edge
- Added `toLocaleString` to ruler numbers so they have a comma
=> fix(ui): design feedback ui tweaks

src-tauri/src/external_dependencies.rs, src-tauri/src/main.rs
- Bring back version 2022 to allowed list
- Make adjustment do `display_name` and `download_url`
- Remove this check for vc version in `dev mode`
=> fix: bring back 2022 vc version requirement

src-tauri/src/gpu_miner.rs
Description
---
fixes: #740 
Remove status monitor after stopping gpu mining.
---
Stop spamming error in console `Error in getting response from XtrGpuMiner status ...`
---
Disabled gpu mining in mining settings and checked if there are still warnings in console.
---
Same as above.
---
=> fix(gpu): clean up gpu status minitor after stopping gpu mining

src/components/CharSpinner/CharSpinner.tsx, src/containers/SideBar/components/Wallet/History.tsx, src/containers/SideBar/components/Wallet/Wallet.styles.ts, src/containers/SideBar/components/Wallet/Wallet.tsx
This PR simplifies the wallet show/hide history animation. I basically removed most of the `layout` props so we have more control over the animation and there's less weirdness.
I changed it so the height of the history container is animated instead of the parent container of the wallet. The parent just adjusts to the new height of the animation automatically as it grows in height. 
I also removed some of the layout animations from the big number, just keeping it on the "tXLM" text.  Less stretching this way, and the show/hide number still looks good
https://www.loom.com/share/a9ee052711f34e429e106394cdc69f2d?sid=2c496820-66b9-4dd1-a726-3739db9d3498
=> fix(ui): simplified sidebar wallet show/hide history animation

src/components/svgs/LoadingSvg.tsx, src/containers/Dashboard/MiningView/components/MiningButton.styles.ts, src/containers/Dashboard/MiningView/components/MiningButton.tsx, src/containers/SideBar/Miner/styles.ts, src/containers/SideBar/components/Wallet/History.tsx, src/containers/SideBar/components/Wallet/Wallet.styles.ts
1. Added a loading state to the Mining Button. 
2. Fixed 1px layout shift when Mining Tiles switched between loading state and showing a number
3. Fixed padding alignment on the wallet history scroll area
=> feat(ui): added loading state to mining button + minor ui polish

src-tauri/Cargo.toml, src/utils/shared-logger.ts, vite.config.ts
Description
---
- update `shared-logger.ts` to pass the log level as `info` when invoking `log_web_message` in local/development because errors are logged to sentry (so this prevents that, but still writes to log files)
- only log vite errors in console
---
- sentry is getting clogged up with local development errors 😬
=> fix: prevent local dev clutter on sentry

src/hooks/airdrop/stateHelpers/useAirdropTokensRefresh.ts, src/hooks/useSetUp.ts
Description
---
- fixed airdrop token refresh interval
- moved out the handle refresh fn to its own hook so it can be called in `useSetup`
---
- lots of errors around fetching the last mined block - after checking it could be that jwts are expired, and the interval in `useAirdropTokensRefresh` wasn't working
=> fix: airdrop token refresh

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/de/Einstellungen.json, public/locales/en/settings.json, public/locales/fr/settings.json, public/locales/hi/settings.json, public/locales/id/settings.json, public/locales/ja/settings.json, public/locales/ko/settings.json, public/locales/pl/settings.json, public/locales/ru/settings.json, public/locales/tr/settings.json, src/containers/SideBar/SideBar.tsx, src/containers/SideBar/components/LowHashRateWarning/LowHashRateWarning.tsx
Description
---
implements: #742 
Adds warning under the mine button about low hash rate.
---
Miner may enter into very slow mining mode if there is not enough free RAM. 
---
Increased hash rate above my CPU capability to trigger warning.
---
Same as above.
---
=> feat: add low hash rate warning

src/components/CharSpinner/CharSpinner.styles.ts, src/components/CharSpinner/CharSpinner.tsx, src/containers/Airdrop/AirdropGiftTracker/components/Gems/styles.ts, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Invite/styles.ts, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/styles.ts, src/containers/Airdrop/AirdropGiftTracker/styles.ts, src/containers/Dashboard/MiningView/components/MiningButton.styles.ts, src/containers/SideBar/Miner/components/ExpandableTile.tsx, src/containers/SideBar/Miner/components/Tile.tsx, src/containers/SideBar/Miner/styles.ts, src/containers/SideBar/components/Wallet/History.tsx, src/containers/SideBar/components/Wallet/HistoryItem.styles.ts, src/containers/SideBar/components/Wallet/Wallet.styles.ts, src/containers/SideBar/components/Wallet/Wallet.tsx, src/containers/SideBar/styles.ts
This PR contains a few minor UI updates to add polish based on design feedback. 
- Adjust font and padding on the sidebar Miner tiles
- Fix line-height issues on Airdrop logged in state
- Shrink sidebar elements so they dont overlap as much on short viewport heights
- Updated bg color on history items to white 0.7
=> fix(ui): more ui polish based on design feedback

src-tauri/src/hardware_monitor.rs, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/utils/auto_rollback.rs, src-tauri/src/utils/mod.rs
Description
---
The frontend was controlling the application initialization process, which means we got caught with some lifecycle issues where a useEffect hook was triggering the `setup_application` invocation multiple times. I added a little debounce mechanism to the call.
We had unnecessary logging, moved some to trace as well as only emit a log if a state has changed.
---
The logs were overflowing with useless information. This just streamlines it a little.
The app was needlessly resetting the application state.
---
I ran the app, the logs are cleaner and there is less duplication of initialization.
---
Run the app, make sure nothing is broken.
---
=> chore(logging): optimize logging and initialization

src-tauri/src/main.rs
An issue was that `InternalWallet::clear_wallet_local_data` was trying to remove cache wallet dir which was opened. I fix it by calling `stop_all_miners` before that action.
=> fix(wallet): import seed words on windows

src-tauri/Cargo.toml, src-tauri/src/binaries/adapter_tor.rs, src-tauri/src/main.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/tor_adapter.rs
```
error[E0382]: use of moved value: `cdn_tor_bundle_url`
--> src/binaries/adapter_tor.rs:29:40
|
21 |         let cdn_tor_bundle_url = format!(
|             ------------------ move occurs because `cdn_tor_bundle_url` has type `std::string::String`, which does not implement the `Copy` trait
...
28 |         for _ in 0..3 {
|         ------------- inside of this loop
29 |             let response = client.head(cdn_tor_bundle_url).send().await;
|                                        ^^^^^^^^^^^^^^^^^^ value moved here, in previous iteration of loop
|
```
=> fix(tor): cdn_tor_bundle_url value moved

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
Description
---
- just removed the unused deps machete flagged (they weren't references anywhere but in the cargo.toml)
=> chore: machete check | remove unused

src/theme/GlobalStyle.ts
I noticed a bug where the drag events on the 3D canvas element were being blocked. `pointer-events: none` was not being respected in the browser. Looks like this Global `all: unset;` declaration was overwriting the `pointer-events` rule on div elements. 
Removing `div` from this reset fixes the issue. `div` elements should not need a reset like this anyways since they don't really have any default styles to begin with. 
https://www.loom.com/share/ed56286a903d4c98b54745732c66a092?sid=31821a02-5d33-47f6-b803-93149a6d2bb1
=> fix(ui): cannot rotate the 3D canvas with mouse drag

package-lock.json, package.json, src/containers/Airdrop/AirdropGiftTracker/sections/LoggedIn/LoggedIn.tsx, src/containers/Dashboard/MiningView/components/BlockTime.tsx, src/containers/Dashboard/SetupView/SetupViewContainer.tsx, src/containers/Settings/sections/experimental/AppVersions.tsx, src/containers/Settings/sections/experimental/MonerodMarkup/MonerodMarkup.tsx, src/containers/SideBar/components/Wallet/SyncTooltip/SyncTooltip.tsx, src/containers/SideBar/components/Wallet/SyncTooltip/styles.ts, src/containers/SideBar/components/Wallet/Wallet.styles.ts, src/hooks/airdrop/stateHelpers/useGetAirdropUserDetails.ts, src/hooks/airdrop/useWebsocket.ts, src/hooks/useHardwareStats.ts, src/store/useAirdropStore.ts, src/theme/types.ts
Description
---
- bump outdated deps (only items not on `wanted` version), no breaking changes
- fixed optional chaining check for `x.gems` stuff (main sentry errors)
- removed uses of `useShallow` since we updated the zustand store create fns and don't need that anymore + it caused one small sentry err
- fixed wallet section tooltip z-index issue
---
- locally
---
- after the next release check that there are no "gems of undefined" or "object has own..... shallow" errors in sentry
- check that the tooltip in the wallet isn't hidden
=> fix: sentry errors

src-tauri/Cargo.toml, src-tauri/src/gpu_miner.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_utils.rs, src-tauri/src/process_watcher.rs
Starts processes in the data dir. On mac I think if you do not specify the starting location of the process, it tries to create the process in the same dir as the application. For Tor and some other processes, they try to create files on startup, and I believe this is the cause of tor not starting on macos.
Also changed the health check to stop on either the health check or a shutdown. Some processes like mmproxy and p2pool have long timeouts for health checks, so these would still be running when the process tried to shutdown.
=> fix: start processes in working dir

src-tauri/Cargo.toml, src-tauri/src/app_config.rs, src/containers/SideBar/components/Wallet/HistoryItem.tsx, src/store/useAirdropStore.ts, src/store/useAppConfigStore.ts, src/store/useShareRewardStore.ts, src/types/app-status.ts
Description
---
- remove sharingEnabled flag from js and move to app_config
- fixed setting the iniiiiiitial `seenPermissions` value and check if already set in `useAirdropStore`
Motivation & context
---
- resolves https://github.com/tari-project/universe/issues/1012
- easier testing
---
- locally
---
- update `sharing_enabled` app_config and check if true/false work as expected
- if it's the very first install permissions toggle should be visible on the setup screen, else it shouldn't be
=> fix(ui): add flag to config & fix permissions toggle init

src/hooks/useMiningMetricsUpdater.ts, src/hooks/useSetUp.ts
basically those changes made it so we never fetched wallet details 
- only use `setSetupDetails` if progress is greater than 0 (since the fetch wallet history call only worked on progress > 0.75 and after setup completed progress went back to 0)
- made the block height check stricter (check that both are not 0)
=> fix: don't set setup progress back to 0

src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs
Cache `get_network_difficulty`  response since it's too heavy to call it every 1sec
=> feat: cache get_network_difficulty response

src/hooks/airdrop/utils/useHandleRequest.ts
[#853](https://github.com/tari-project/universe/issues/853)
Description
---
We have observed a some number of 401 responses from airdrop requests in Sentry. My previous pr (https://github.com/tari-project/universe/pull/1079) should solve this issue.
I'm additionally adding a check for token expiration.
=> fix: check token expiration before airdrop request

src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/process_watcher.rs
Upgrades to v1.9.0. 
It also fixes a bug where it would not detect a corrupt database. Not sure how this was working before. But if the database was corrupt (or not compatible), it should delete the node database and resync.
BREAKING CHANGE: The hard fork on minotari_node means that the chain needs to be synced again. This will happen automatically, but note that start up will be longer
=> fix!: fix check for database corruption

.prettierignore
Whenever I make a change to the translation `json` files in `/public/locales/en/*.json` it changes the format for the whole file, which is annoying and a little risky. Merge conflicts are more common and we should be able to track the specific changes within these files when doing code review. 
My solution is just to have Prettier ignore these translation files. Alternatively, to solve this problem we could update all automation scripts to match our prettier settings... but this is simpler. 
Let me know if your thoughts on this change, any objections?
=> chore: add translation content json files to .pretterignore

src-tauri/src/main.rs, src-tauri/src/node_manager.rs, src/containers/main/SideBar/components/OrphanChainAlert.tsx
Description
---
Check if node is synced before validating block hash against text explorer and fix bug where warning was shown even after node was no longer an orphan chain.
---
Many users reported false positive where they had warning but they were sure it wasn't the case. This could be achieved if user disconnected internet connection and connected again.
---
Disconnect WiFi and connect again. While disconnected there should be warning but after connecting it should go away after 1 minute max.
---
Same as above.
---
=> fix(orhpan-chain): verify node is synced before checking if it's orphan chain

src/containers/main/SideBar/components/Wallet/HistoryItem.styles.ts, src/containers/main/SideBar/components/Wallet/HistoryItem.tsx
Description
---
- moved the parent hover style reference and added to the right side items too
- noticed while testing the `showShareButton` check meant the replay button would also be hidden if you weren't logged in with airdrop so fixed up those checks too
---
| half of the history item styling wasn't updated on hover |
| :---: |
| ![image](https://github.com/user-attachments/assets/874d0597-b9b4-431b-a228-ebeb27e9c1e9) |
---
- locally:
https://github.com/user-attachments/assets/e9a39322-addd-4c2f-ba04-eb06816bcf34
https://github.com/user-attachments/assets/fbf12ee8-2f34-41bf-be67-965e7dabd52e
https://github.com/user-attachments/assets/923a4a46-34ec-43ed-bf8e-17599258f612
**(only to show animation change:)** …
=> fix(ui): history item

src-tauri/Cargo.toml, src/App/AppWrapper.tsx, src/App/sentryIgnore.ts, src/components/dialogs/RestartDialog.tsx, src/components/dialogs/SendLogsDialog.tsx, src/containers/floating/CriticalErrorDialog/CriticalErrorDialog.tsx, src/containers/floating/ExternalDependenciesDialog/ExternalDependenciesDialog.tsx, src/containers/floating/ExternalDependenciesDialog/ExternalDependencyCard.tsx, src/containers/floating/PaperWalletModal/sections/ConnectSection/ConnectSection.tsx, src/containers/floating/Settings/sections/airdrop/ApplyInviteCode.tsx, src/containers/floating/Settings/sections/experimental/TorMarkup/TorMarkup.tsx, src/containers/floating/Settings/sections/general/LogsSettings.tsx, src/containers/floating/Settings/sections/general/ResetSettingsButton.tsx, src/containers/floating/Settings/sections/p2p/P2poolStatsMarkup.tsx, src/containers/floating/Settings/sections/wallet/SeedWordsMarkup/useGetSeedWords.ts, src/containers/main/SideBar/Miner/components/CustomPowerLevels/CustomPowerLevelsDialog.tsx, src/containers/main/SideBar/Miner/components/CustomPowerLevels/CustomPowerLevelsDialogContainer.tsx, src/containers/main/SideBar/Miner/components/CustomPowerLevels/RangeInput.tsx, src/hooks/airdrop/stateHelpers/useAirdropUserPointsListener.ts, src/hooks/airdrop/utils/useHandleRequest.ts, src/hooks/mining/useTransactions.ts, src/hooks/useMiningMetricsUpdater.ts, src/hooks/useSetUp.ts, src/hooks/useUpdateStatus.ts, src/store/appStateStore.ts, src/store/useAirdropStore.ts, src/store/useAppConfigStore.ts, src/store/useMiningStore.ts, src/store/useP2poolStatsStore.ts, src/store/useWalletStore.ts
Description
---
noticed the actual error from BE wasn't logged in sentry re. paper_wallet details, then noticed the amount of duplications
- removed `Sentry.captureException(`s in each `catch` because we are already using the `captureConsoleIntegration` 
- added ignore for all the `"Already getting ...."` warnings from BE which are being logged as errors clogging up sentry
- made sure all `console.error`s have a short description and are passing the error through
- fixed lints
=> chore: dedupe sentry logging | ignore already getting x warns | fix lints

src/hooks/useUpdateStatus.ts
Description
---
There was an issue with auto-update checker executed multiple times which led to executing auto-update multiple times in the same time
See logs:
```
[Log] INITIAL CHECK (useUpdateStatus.ts, line 129)
[Log] INITIAL CHECK (useUpdateStatus.ts, line 129)
[Log] INITIAL CHECK (useUpdateStatus.ts, line 129)
[Info] New Tari Universe version available – Object (useUpdateStatus.ts, line 94)
[Info] New Tari Universe version available – Object (useUpdateStatus.ts, line 94)
[Log] INITIAL CHECK FLAG SET TO FALSE (useUpdateStatus.ts, line 131, x2)
[Info] New Tari Universe version available – Object (useUpdateStatus.ts, line 94)
[Info] Proceed with auto-update (useUpdateStatus.ts, line 99)
[Info] Updater event – null – "PENDING" (useUpdateStatus.ts, line 121)
[Log] INITIAL CHECK FLAG SET …
```
=> fix: auto updater triggered multiple times

src-tauri/src/app_config.rs
Description
---
We've found with @Misieq01 what's causing the `app_config` overrides. It's because older versions have: `custom_max_gpu_usage: Option<u32>`(which is `null` as default). It was later changed to `custom_max_gpu_usage: Vec<GpuThreads>`(which is `[]` by default). It was treated as types inconsistency by serde which led to using and saving default app config
=> fix: app_config overrides

src-tauri/src/node_manager.rs, src-tauri/src/process_watcher.rs
This exit was added so that we can detect when the base node stops on error 114 so that we can delete the previous database and resync. However, the GPU miner would exit with a weird error code and then it would not be restarted.
=> fix: change only minotari node to stop on error 114

src/containers/main/SideBar/Miner/components/CustomPowerLevels/CustomPowerLevelsDialog.tsx, src/containers/main/SideBar/Miner/components/CustomPowerLevels/RangeInput.styles.ts, src/containers/main/SideBar/Miner/components/CustomPowerLevels/RangeInput.tsx
Description
---
- fixed slider's thumb styling so that isn't all a lighter opacity when `disabled` (`isLoading`) - only lighten the border
- also added a helper to get a "safe" value based on the range slider steps, because i noticed the GPU threads initial value was an odd number, and i could slide to an odd number,  but that should only increment in steps of two
---
- resolves https://github.com/tari-project/universe/issues/1121
---
- locally:
https://github.com/user-attachments/assets/e40c6653-d74e-4083-a3e5-5592e576800b
---
1. see ticket
2. see that GPU settings can't set to an odd number
=> fix(ui): slider disabled styling

src-tauri/capabilities/default.json, src-tauri/src/commands.rs, src-tauri/src/hardware/hardware_status_monitor.rs, src-tauri/src/main.rs, src-tauri/src/progress_tracker.rs, src/hooks/app/useSystemTray.ts, src/hooks/mining/useEarningsRecap.ts, src/store/useBlockchainVisualisationStore.ts, src/utils/systray.ts
Description
---
---
---
- add actions to un/minimize in systray
---
---
=> chore(ui): tauri v2 upgrade cleanups

src-tauri/src/commands.rs, src-tauri/src/main.rs
Description
---
- add back missing `external_dependencies` imports with lint comments for windows
---
fixes this:
---
running `cargo check` locally (i'm on mac)
=> fix: missing imports for windows

src-tauri/src/binaries/binaries_manager.rs, src-tauri/src/binaries/binaries_resolver.rs, src-tauri/src/commands.rs, src-tauri/src/download_utils.rs, src-tauri/src/main.rs, src-tauri/src/progress_tracker.rs
Description
---
Timeout if initialization took too long and report to sentry the last action. Timeout is for each binary and is set to fixed value of 5 minutes.
Another big change is that app will exit and show error if timeout was exceeded. Previously user would be stuck at initialization screen.
Closes: https://github.com/tari-project/universe/issues/1170
---
Some users reports being stuck at initialization screen. The underlying reason is unknown and we need to increase the logging and sentry reporting.
---
Decrease timeout to like 20 seconds and add this line in `binaries_resolver.rs` in `initialize_binary` function to fake timeout on one selected binary:
```rust
match binary {
Binaries::Xmrig => {
println!("Sleeping for 30 seconds"); …
```
=> feat: timeout and log latest action during init

src/containers/floating/Settings/sections/p2p/P2pMarkup.tsx, src/containers/floating/Settings/sections/p2p/PoolMiningSettings.tsx
#1208
Description
---
P2pool stats should be visible only after restarting the app, when toggled on
[Screencast from 12-06-2024 12:00:40 PM.webm](https://github.com/user-attachments/assets/3114cb1c-aa58-47cc-88c3-0ac182acfcf5)
=> fix(ui): hide p2p stats when p2poll toggled

src-tauri/src/node_manager.rs
Currently, this sentry log is duplicated as a new sentry event for each instance. This is an attempt to group them together into a single log, but include the data
=> fix: reduce orphan chain sentry logs into one

.github/workflows/release.yml
Description
---
`AutoUpdate error: Could not fetch a valid release JSON from the remote` is a recurring issue reported on Sentry. Unfortunately, I have limited information regarding the response itself. My assumption is that GitHub releases may occasionally restrict access for certain users. I decided to set an additional endpoint for `latest.json` from our CDN, which will be utilized only when the GitHub endpoint is inaccessible(a non-2XX status code is returned).
=> chore: additional latest json url from cdn

.github/workflows/release.yml, src-tauri/tauri.conf.json
Description
---
- fixes missing release artifacts after Tauri V2 merge:
needed to change `createUpdaterArtifacts` to [`v1Compatible`](https://tauri.app/plugin/updater/#building) for the zips
---
-  beta build branch:
macOs: 
linux:
windows: 
---
- check artifacts in [the release workflow](https://github.com/tari-project/universe/actions/runs/12294412932)
=> fix: updater artifacts V1 compatible

src/components/AdminUI/groups/OtherUIGroup.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/LoggedIn.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Flare/BonusGems/BonusGems.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Flare/Flare.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Flare/FriendAccepted/FriendAccepted.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Flare/GoalComplete/GoalComplete.tsx, src/hooks/airdrop/stateHelpers/useAirdropUserPointsListener.ts, src/hooks/airdrop/stateHelpers/useGetReferralQuestPoints.ts, src/store/useAirdropStore.ts
Description
---
- cleaned up animation timeouts (couldn't repro the original issue but there was an issue of the animaions not actually going away which was reporoducable every time)
- cleaned up the `useAirdropUserPointsListener` listener and how the zustand store was updated there:
- biggest one being the check against the count from the payload vs the store - made sure to only update the store after
- added triggers for the animations for very BASIC testing in the admin ui (not that helpful since it's not directly related to the points)
---
- resolves an issue picked up when checking https://github.com/tari-project/universe/issues/1238, but should also hopefully resolve that issue. couldn't reproduce but it's all related to the listener and the timeouts being …
=> fix: gem sidebar animations

.github/workflows/release.yml, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
- use dev version of `tauri-apps/tauri-action` [context](https://github.com/tauri-apps/tauri-action/issues/975)
- use original signing pubkey
- bump to 0.8.20
=> ci: fix Tauri V2 release artifacts

src-tauri/src/p2pool/models.rs, src-tauri/src/p2pool_adapter.rs
Adds a check that p2pool has received a gossip message and has at least one connection, otherwise returns Warning during the health check. 
Reminder: if a certain number of health checks return Warning in a row, then it will be restarted.
=> feat: better p2pool health check

src-tauri/src/node_manager.rs, src/App/AppWrapper.tsx
Description
---
Allow the base node more time to setup before qualifying it as bad.
Prevent sentry/vite from crashing the front end.
fixes: #1275
fixes: #1269
fixes: #1273
---
Fix bug preventing use of the app
---
Manually
---
- Setup, and not run into the 30% bug.
- Run on windows for 2+ hours and not crash
- See the settings panel on windows not be slow
=> fix: base node setup time & app crashing

src-tauri/src/telemetry_manager.rs
Description
---
coinbase '=' padding character caused an issue where an alternative string was written to the blockchain
---
Invalid id written to the chain.
---
On esmeralda with a local build.  
---
Check the coinbase extra string that gets written to the block and compare that to what the merge mining proxy gets as an arg.
---
=> fix: coinbase padding

src-tauri/Cargo.lock, src-tauri/Cargo.toml
Tauri has a bug in it which causes it to panic. I've created a PR to fix it (https://github.com/tauri-apps/tauri/pull/12000) but it might take a while for them to merge it and release a new version. In the meantime, we can switch to using our fork.
=> fix: use tari's fork of tauri

src/containers/floating/Settings/sections/p2p/PoolMiningSettings.tsx, src/store/useUIStore.ts
#1208
Description
--
Disabled p2pool flag wasn't stored in store since user could close/reopen p2pool stats and crash the app after switching it on.
Testing
--
1. Run app with p2pool disabled
2. Enable p2pool mining, cancel restarting
3. Close and reopen settings view
4. App shouldn't crash
=> fix: p2pool stats crash

src-tauri/src/commands.rs
Description
---
Seeing errors in Sentry where the main window can't be fetched. Retry for a second before panic'ing.
---
A brief delay between window creation and closing may help alleviate the error.
---
Error isn't present locally so 🤞🏻
=> fix: retry window fetching

src/containers/main/Airdrop/AirdropGiftTracker/components/ClaimModal/ClaimModal.tsx, src/containers/main/Airdrop/AirdropGiftTracker/components/ClaimModal/styles.ts
This PR removes the "X" logo from the `Claim Gems` button in the login modal. This is because we now support multi-auth logins. 
I also added `preventDefault` and `stopPropagation` to see if it fixes an issue where this button is not working on Linux. I don't have access to a Linux machine to test, so this is a shot in the dark fix. This is low risk though, since adding those event functions shouldn't effect anything on the working platforms.
=> fix(ui): removed X logo from claim gems and possible linux click fix

.github/workflows/ci.yml, ci/windows-dev-environment-notes.md
Description
---
Fix broken CI builds. We suffered two different errors (below), for relatively unknown reasons. To get past the errors I've turned bundles off in the `tauri-build` workflow. We don't need these bundles made. The workflow still does a test release compile. it just isn't packaging the build for any specific platform anymore.
Version was bumped here: https://github.com/tari-project/universe/pull/1349 to resolve a previous error.
First error
```
error: failed to compile `tauri-cli v2.2.2`, intermediate artifacts can be found at `/tmp/cargo-install8JNgkx`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
rustc 1.80.0 is not supported by the following package:
home@0.5.11 requires rustc 1.81
```
Second …
=> chore: don't make bundles for every PR

src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/commands.rs, src-tauri/src/main.rs, src-tauri/src/p2pool/models.rs, src-tauri/src/p2pool/stats_client.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/telemetry_manager.rs
1. add squad to p2pool for telemetry
2. change p2pool to latest version
3. change minotari suite to latest version
4. change p2pool stats to use tokio::watch instead of polling (this means fewer requests to p2pool)
=> feat: add squad to p2pool

src-tauri/src/wallet_adapter.rs
Description
We've been clearing the wallet database on startup which forced scanning UTXOs from the tip 0 on every run. Scanning takes really long time each run:
```
DEBUG Scanning round completed up to height 84661 in 440.07s (2116869 outputs scanned, 1478 recovered with value 1479069.697509 T)
```
Clearing was done when we had issues with view keys. Since it's gone, we can keep wallet dir and support caching.
---
I tested manually by running the app several times and watching wallet logs(base_layer.log) to check whether wallet uses previously scanned blocks. 
```
Scanning round completed up to height 85291 in 301.62ms (70 outputs scanned, 0 recovered with value 0 µT)
```
I also played with displaying seed words and importing new wallets to ensure everything is …
=> chore: prevent from clearing wallet data after restart

.github/workflows/release.yml, src-tauri/src/app_in_memory_config.rs, src/containers/floating/Settings/sections/airdrop/ApplyInviteCode.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedOut/LoggedOut.tsx
Description
---
Removes deprecated url config variable.
---
The project switched to the new auth system, which is available through the website url.
---
local Tari universe, with the combination of both airdrop local and airdrop production versions.
---
The reviewer should start up the app and be able to log in to the airdrop game without any issues.
---
=> fix: remove old auth url

src-tauri/src/auto_launcher.rs, src-tauri/src/main.rs, src/App/AppWrapper.tsx, src/hooks/app/isAppReady.ts
Description
---
- removed a redundant log from auto launcher flow
- updated the `frontend_ready` x `app_ready` emits:
* separated them, moved FE `emit` to `AppWrapper`
* changed the `app_ready` (FE) listener to use `once`
* also changed the `frontend_ready` (BE) listener to use `once`
Motivation and Context + How Has This Been Tested?
---
locally
| before: |
| --- |
| ![before](https://github.com/user-attachments/assets/61f7aef1-3051-4ed1-b1e7-ea55acfd299b) |
| after: |
| --- |
| ![29555](https://github.com/user-attachments/assets/47adcd99-df96-4696-a6c6-5c73ff1f1b27) |
---
- run locally
- compare terminal logs to when running latest main locally
=> refactor: emit and logging cleanup

src/containers/main/Airdrop/AirdropGiftTracker/components/Gems/Gems.tsx, src/containers/main/Airdrop/AirdropGiftTracker/components/Gems/styles.ts
This PR fixes the layout shifting on the Gems animated number. using `NumberFlow` would also fix this, but i'm adding this as a quick little improvement while we wait for the full integration of `NumberFlow`. 
Here's a video showing the improvement. It shows the current version at first, then the improved version at the 8 second mark. 
https://github.com/user-attachments/assets/3f6e9553-31b0-4141-8230-82ca2dde07a0
=> fix(ui): fix layout shifting on gems number animation

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/commands.rs, src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/tests/app_config_tests.rs
Description
---
Added the new base node gRPC call `get_network_state` to `fn get_network_hash_rate_and_block_reward` that returns all required base node statuses in a single call.
**The new base node gRPC call `get_network_state` came with the new Tari base layer nextnet release, `v1.10.0-rc.0`**
`MinerMetrics` now has additional members
- `initial_sync_achieved` (renamed from `is_synced`, describing the actual status)
- `failed_checkpoints`
- `base_node_state` 
and also provides a method `MinerMetrics::is_synced()` that will return the is-synced status based on the `base_node_state`.
**Notes:** 
- New `MinerMetrics` must be wired into the code where applicable.
---
To implement the new more efficient base node gRPC method call
---
CI
What …
=> feat: add new base node grpc call with new nextnet release

.github/workflows/release.yml
Description
Add linux arm64 build
Support Raspberry Pi and possible Asahi Linux devices 
Only build tested, not yet run on Raspberry Pi or an Asahi Linux device.
=> chore(ci): add linux arm64 build

src-tauri/src/main.rs, src-tauri/src/telemetry_service.rs
Description
---
Fixes #1404
Makes field `app_id` have the same value as in the telemetry manager.
---
This allows to make more in depth analysis of users bug reports. 
---
Added line to print `app_id` just before sending telemetry event in both telemetries and confirmed they are equal.
---
Same as above
---
=> fix(telemetry-service): make app_id the same as in telemetry manager

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/capabilities/default.json, src-tauri/src/main.rs, src/containers/floating/PaperWalletModal/sections/QRCodeSection/QRCodeSection.tsx, src/containers/floating/Settings/sections/wallet/SeedWordsMarkup/SeedWordsMarkup.tsx, src/containers/floating/Settings/sections/wallet/SeedWordsMarkup/useGetSeedWords.ts, src/containers/floating/ShareRewardModal/ShareRewardModal.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/Invite/Invite.tsx, src/containers/main/ShellOfSecrets/SoSWidget/segments/Friends/Friends.tsx, src/hooks/helpers/useCopyToClipboard.ts
Description
---
- use tauri's clipboard plugin instead of `navigator.clipboard` (there was a permissions error the first time trying with navigator 🤷🏼 )
---
#1409 
---
locally:
https://github.com/user-attachments/assets/9eb08fac-5656-4a84-935e-8d994305a47c
---
- start app
- click copy seed words (before viewing them)
=> fix: seedword copy

src-tauri/src/main.rs, src/components/AdminUI/groups/DialogsGroup.tsx, src/components/elements/buttons/BaseButton.styles.ts, src/components/elements/buttons/ExtendedButton.styles.ts, src/components/elements/buttons/button.types.ts, src/containers/floating/ExternalDependenciesDialog/ExternalDependenciesDialog.tsx, src/hooks/app/useListenForExternalDependencies.ts, src/store/appStateStore.ts, src/store/useUIStore.ts
Description
---
- add flag (`has_missing_dependencies`) to state for missing deps to emit after FE ready
- fix missing key in dialog and button x theme issues
---
https://github.com/tari-project/universe/issues/1421
=> fix: missing dependency dialog | add flag to state for missing deps to emit after FE ready

public/locales/en/components.json, src/containers/floating/LudicrousCofirmationDialog/LudicrousCofirmationDialog.tsx
The Ludicrous warning modal cancel button used to say "Revert to Eco". That wording was misleading since the user wasn't really "reverting" anything. This change makes the button work for both Eco mode and Custom mode and it acts as a clear "Opt-out" for Ludicrous mode. 
I also changed the title of the modal from "Stay in Ludicrous Mode?" to "Switch to Ludicrous Mode?".
=> fix(ui): change wording on ludicrous warning modal cancel button

src-tauri/src/credential_manager.rs
Fix: [#1418](https://github.com/tari-project/universe/issues/1418)
Platform: **MacOS**
Description
---
Create parent directory(`com.tari.universe` or `com.tari.universe.alpha`) when doesn't exist yet.
---
App panics when user denies keychain prompt on first run(fresh install). It happens because of:
```
failed to open file: Os { Code 2, kind: NotFound, message: "No such file or directory"}
```
file that app wants to open: `/com.tari.universe/credentials_backup.bin`
```
let mut file = OpenOptions::new()
.write(true)
.create(true)
.truncate(true)
.open(self.fallback_file())?;
file.write_all(&serialized)?;
```
Note from std file docs: `Depending on the platform, this function may fail if the full directory path does not exist.`
What process can a PR reviewer use to …
=> fix: first run when denied keychain prompt

.github/workflows/release.yml
Description
Add a best effort option - enabled for linux-arm64
Put an option in place, so that less focus builds don't break the release
Builds in local fork, have not had linux-arm64 fail (not seen in testing)
=> chore(ci): add a best effort option, enabled for linux-arm64

public/locales/en/airdrop.json, src/containers/main/Airdrop/AirdropGiftTracker/AirdropGiftTracker.tsx
We received an updated copy deck, just updating the test to reflect the latest approved copy.
=> fix(ui): update airdrop login module copy again

src-tauri/Cargo.lock, src-tauri/Cargo.toml
Solves: [#1347](https://github.com/tari-project/universe/issues/1347)
Platform
---
**LINUX ONLY**
Description
---
Utilize `linux-native-sync-persistent` to ensure that storage remains intact between shutdowns.
---
Seed words were inaccessible after shutting down the Linux machine. The `linux-native` feature does not offer persistent storage, resulting in storage loss upon shutdown.
---
LINUX: Restart the machine and check if the seed words are accessible
=> fix: use linux-native-sync-persistent for keyring

package.json, src-tauri/tauri.conf.json
Description
---
tower animation `.buf` files are inlined (no way around this with lib mode) 
- added `application/octet-stream` & `base64` to `data` optin for `connect-src` in CPS config
---
- animation broken on 0.9.12
---
- locally (dev) and with local builds
=> fix: add application/octet-stream and base64 to CSP

.github/workflows/release.yml
Description
Add windows signature verification
Split up sentry install and upload
Make sure Windows MSI is correctly signed
Make sure Windows debug symbols for sentry are upload 
Testing in branch, works as expected
=> chore(ci): add windows sig verification and split up sentry steps

package-lock.json, package.json, src-tauri/tauri.conf.json
Description
---
- bump styled-components
- remove unnecessary CSP config items 
---
- wasm CSP breaks old mac builds
---
- created local builds with updates - only to ensure that it still builds as normal, i can't confirm with certainty that this resolves the issue on older macs
=> fix(ui): remove wasm related csp config

src/components/transactions/history/HistoryList.tsx, src/components/transactions/history/ListItem.styles.ts, src/components/transactions/history/ListItem.tsx, src/components/transactions/send/Send.tsx, src/components/transactions/types.ts, src/store/useBlockchainVisualisationStore.ts, src/store/useWalletStore.ts, src/types/transactions.ts
Description
---
For the first iteration, display mocked pending transaction which is replaced with the corresponding tx when it's mined.
Screencast:
https://github.com/user-attachments/assets/13c6e77b-5e33-4f09-92b8-a5fa9148ff24
=> feat: display mocked pending tx

src-tauri/src/commands.rs, src-tauri/src/main.rs, src-tauri/src/utils/address_utils.rs, src-tauri/src/utils/mod.rs, src/types/invoke.d.ts
Address validation method for send 
```
try {
await invoke('verify_address_for_send', {address});
console.log("address validated");
} catch (error) {
console.error('Error verifying address:', error);
}
```
=> chore(quick load): address validation command

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/de/settings.json, public/locales/en/settings.json, public/locales/fr/settings.json, public/locales/hi/settings.json, public/locales/id/settings.json, public/locales/ja/settings.json, public/locales/ko/settings.json, public/locales/pl/settings.json, public/locales/ru/settings.json, public/locales/tr/settings.json, src-tauri/src/events.rs, src-tauri/src/events_emitter.rs, src-tauri/src/events_manager.rs, src-tauri/src/node/node_adapter.rs, src-tauri/src/node/node_manager.rs, src-tauri/src/setup/phase_node.rs, src/containers/floating/Settings/sections/connections/Node.tsx, src/hooks/app/useTauriEventsListener.ts, src/store/useNodeStore.ts, src/types/backend-state.ts, src/types/events-payloads.ts
* Add local node syncing status in settings when synced in the background
* use note types as Remote and Local only
* fix displaying Block sync progress(local header was incorrect)
=> feat(quick-load): show background node sync status

src/components/transactions/wallet/Wallet.tsx
Description
---
Hide Send/Receive buttons for non-dev envs. Instead display a paper wallet button.
DEVELOPMENT
NON-DEVELOPMENT
=> feat(quick load): show send receive only on dev

src/App/App.styles.ts, src/App/App.tsx, src/components/CharSpinner/CharSpinner.tsx, src/components/transactions/components/Tabs/tab.styles.ts, src/types/invoke.d.ts
could not reproduce after the first time it happened, but this is the only thing i could think of MAYBE having an impact on which screens show up after the splash screen :/ 
just removed the `const CurrentAppSection = function CurrentAppSection({....` left over from when it was memoized. 
the rest of the changes are just lint fixes
=> fix(quick-load): lone tower

src-tauri/src/app_config.rs, src-tauri/src/configs/config_core.rs, src-tauri/src/configs/config_mining.rs, src-tauri/src/configs/config_ui.rs, src-tauri/src/configs/config_wallet.rs, src-tauri/src/configs/trait_config.rs, src-tauri/src/configs/trait_config_test.rs, src-tauri/src/setup/setup_manager.rs
- Changed `load_or_create` method in `app_config` to prevent creating new default config file with each start
- When `app_config` is present it will be loaded and then migrated to new configs
- When `app_config` is not present migrations will be skiped and `is_migrated` flag will be set to `true`
- If `app_config` is present it will be moved to `{configs_location}/old/app_config.json` after migrations
=> fix: [ quick load ] hide old app_config.json

src-tauri/src/events_manager.rs
Wallet scanning takes long time when scanning with the remote node. It's safe to increase timeout, because bad state will immediately stop it.
=> feat(quick load): increase wallet scanning timeout

src/containers/main/Sync/components/Progress.tsx, src/containers/main/Sync/sync.styles.ts, src/store/actions/miningMetricsStoreActions.ts
Description
---
- adjust `gap` and header image sizing on the syncing screen
- set the whole base node status in `handleBaseNodeStatusUpdate`
---
https://github.com/tari-project/universe/issues/1831
---
https://github.com/user-attachments/assets/9079a731-d05d-4771-a8f3-82235022ef56
=> fix(quick-load): ui issues - smaller screens and missing hashrates

src-tauri/src/node/node_adapter.rs, src-tauri/src/node/node_manager.rs, src-tauri/src/setup/phase_node.rs
* Handle corrupted state
* Solve problems when node hasn't started yet and we treat it as unhealthy
* wait 60sec before propagating warnings for node healthcheck
* `wait_ready` waits for both local and remote node for RemoteUntilLocal
* wait ready stops on shutdown signal
=> feat(quick load): fix node connection issues and corrupted db

src-tauri/src/setup/phase_node.rs
Description
---
Reduce high CPU usage, comparison is visible on these screenshots:
before:
and after:
---
Spawned loop in `phase_node` was being polled constantly without any delay, causing my app to use 15% of all CPU without any mining.
Here is comparison between polling same future before and after:
before:
after:
---
Run TU on feature branch and measure CPU usage while not mining and compare it with this branch.
---
Same as above.
---
=> fix: phase node high cpu

src/containers/floating/Settings/components/LanguageDropdown.tsx
Description
---
Fixes #1670 
---
Component did not re-render after changing language since language selection was out of app store and component didn't detect language change.
---
Run locally and change language and check selected language in dropdown.
---
Same as above.
---
=> fix: language selection dropdown

src/components/transactions/components/TxInput.style.ts, src/components/transactions/components/TxInput.tsx, src/components/transactions/send/FormField.tsx, src/components/transactions/send/Send.tsx
I've improved the error message UI for the Send form fields. The errors now animate and are part of the Input components. This provides more context to the user and looks much better visually.
=> fix(ui): better send form field error message ui

src-tauri/src/app_config.rs, src-tauri/src/feedback.rs, src-tauri/src/main.rs, src-tauri/src/telemetry_manager.rs
- Replaced old app_config with new ones in `telemetry_manager` and `feedback`
- Added warnings to all get/set methods in `app_config`
=> fix: [ quick load ] remove appconfig from telemetry

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
Description
---
Fix 10 minute shutdown after remote node become unhealthy.
```
15:31:18 INFO  Triggering shutdown for Common processes
15:31:18 INFO  Triggering task close for Common processes
15:31:18 INFO  TelemetryManager::start_telemetry_process has been cancelled by app shutdown
15:31:18 INFO  Shutdown signal received. Stopping periodic updates.
15:31:18 INFO  Waiting for Common processes to finish
15:31:21 ERROR remote_minotari_node is not healthy: health check timed out
... 10 minutes of same error message ...
15:41:36 ERROR remote_minotari_node is not healthy: health check timed out
15:41:39 ERROR Error getting connected peers
15:41:39 ERROR Unknown error: status: Unavailable, message: "grpc-status header missing, mapped from HTTP status code 502", details: [], metadata: …
```
=> fix: await connected peers shutdown

.github/workflows/release-exchange.yml, exchanges.json
- Added new job for reading exchanges.json
- Extended matrix to include all exchanges
- Added steps for uploading artifacts either to github or aws
- Adjust exchanges.json file with id that is present on cms
- Add repository secrets for each secret_name in the file
- release-exchange.yml and release.yml have duplicated code, implement solution for it
- Handle updater files for each exchange miner
=> feat: exchange multiple ci

package-lock.json, src-tauri/src/commands.rs, src-tauri/src/configs/config_wallet.rs, src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/setup/phase_unknown.rs, src-tauri/src/setup/setup_manager.rs
Description
---
Cpu mining config was importing wallet address at initialization was wouldn't update even after changing address.
=> fix(exchange-miner): rely on single source of truth for tari wallet address

src-tauri/src/commands.rs, src-tauri/src/setup/setup_manager.rs
- Replaced enum for modal status ( `PhaseStatus` => `ExchangeModalStatus` )
- Change behavior to only blocking entering to the main screen when the exchange address is not set instead of blocking unknown_phase execution
=> fix: [ exchange miner ] improve modal status handling

src-tauri/src/events_manager.rs
Description
---
Omits coinbase check in exchange miner. This should exists since wallet isn't initialized and we don't care about coinbase in miner blocked but also fixes error `ERROR Error waiting for wallet scan: Wallet not started`.
=> fix(exchange-miner): ignore coinbase check

src-tauri/src/commands.rs
- `stop_cpu_mining` currently stops both cpu and gpu miners
=> fix: adjust stop_cpu_mining

.github/workflows/release-exchange.yml, .github/workflows/release.yml
Description
---
Remove rpm builds. They aren't added to the site to download, only available on github. They take way too long to make and aren't worth the free CI time.
=> chore: remove rpm builds

src-tauri/src/airdrop.rs, src-tauri/src/commands.rs, src-tauri/src/mm_proxy_manager.rs
- After connecting to airdrop there is a need to restart `mmproxy` to obtain new `unique_string` based on airdrop values
- If mining then we were stopping it, then changing `mmproxy` config and restarting `mmproxy`, at the end starting mining again
- There was a problem with obtaining `mmproxy` config which resulted in error so mining didn't started again
- Starting / Stopping mining from backend **does not influence UI** states on frontend which resulted in constant load
- Switched to the **restart phase implementation** from `setup_manager`, and just restarted `mining_phase` which then should pass newest `unique_string` to `mmproxy` and handle mining flow properly
Fixes: #2327
=> fix: adjust restart behaviour for mmproxy during airdrop connect

src/store/useBlockchainVisualisationStore.ts
The recent change (wait 3 blocks before the win animation) disrupted the “expected” update flow, causing significant updates to be delayed/messed.
My fix solves the problem when winning a block does not update block_height until 3 confirmations met - then updates to the tx mined block which is 2 blocks behind
It solves following problem:
1. Block n won - block height not updated(= n - 1)
2. Block n + 1 lost - block height updated to n + 1(updated +2)
3. Block n + 2 lost - block height updated to n + 2(updated + 1)
4. Block(n) met 3 confirmations after winning - updated block height to **n** which is 2 blocks behind
My fix updates block height even though it's won(it's not updated later)
----------
This change has several other issues when won a block:
* received funds aren't visible for …
=> fix: update block height when block mined

src-tauri/src/configs/config_wallet.rs, src-tauri/src/setup/phase_wallet.rs
Simply bump `wallet_migration_nonce` in config wallet to remove wallet related data and trigger full scan etc.
```
// Bump to force wallet full scan
const WALLET_MIGRATION_NONCE: u64 = 1;
```
```
13:59:33 INFO  Wallet migration required(Nonce 0 => 1)
```
=> feat: wallet migration nonce

src-tauri/src/node/node_manager.rs, src-tauri/src/setup/setup_manager.rs
Description
---
Node timeouts set to: 
* processing refs and returning indentity - 420sec(7mins)
* expected node startup time(being healthy == returning state) - 540sec(9mins)
* node phase timeout - 15mins(mainly for peer connection)
=> fix: increase timeout to process payrefs

src/components/exchanges/LinkModal/LinkModal.tsx, src/components/exchanges/connect/Connect.tsx, src/components/exchanges/universal/clipboardViewer/styles.ts, src/components/exchanges/universal/option/XCOption.tsx, src/components/exchanges/universal/option/styles.ts, src/components/exchanges/universal/options/Options.tsx, src/components/exchanges/universal/options/styles.ts, src/components/transactions/wallet/Exchanges/ExchangesUrls.tsx, src/components/transactions/wallet/Exchanges/exchange-button/ExchangeButton.tsx, src/components/wallet/components/details/WalletDetails.tsx, src/components/wallet/components/details/styles.ts, src/components/wallet/sidebarWallet/SidebarWallet.tsx, src/containers/floating/EXModal/EXModal.tsx, src/containers/floating/UniversalEXSelectorModal/UniversalEXSelectorModal.tsx, src/containers/floating/UniversalEXSelectorModal/styles.ts, src/hooks/exchanges/fetchExchangeContent.ts, src/hooks/exchanges/fetchExchanges.ts, src/store/actions/appConfigStoreActions.ts, src/store/actions/walletStoreActions.ts, src/store/useExchangeStore.ts
Description
___
- use `useQuery` for fetching exchange data (so no need to restart if new ones are added/assets change)
- ui cleanups in wallet and modal 
- mostly theming
=> feat(ui): useQuery for xc data + more ui cleanups

src/components/wallet/components/details/WalletDetails.tsx, src/components/wallet/components/details/styles.ts
Description
---
Fix 'Mining here' text to fix color on both themes:
=> fix(exchange-miner): change 'mining here' text to fixed color on both themes

src/components/exchanges/universal/option/XCOption.tsx, src/hooks/exchanges/fetchExchangeContent.ts, src/store/actions/appConfigStoreActions.ts
Description
---
- removed `setCurrentExchangeMinerId` from the fetch query - only set in `handleExchangeIdChanged` and when coming back from seedless ui
---
- local builds
=> fix: fetching content between builds

src/components/wallet/components/details/actions/WalletCardActions.tsx, src/containers/navigation/Sidebars/BridgeNavigationButton.tsx, src/containers/navigation/Sidebars/NavigationButton.tsx, src/hooks/mining/useMiningUiStateMachine.ts, src/store/actions/uiStoreActions.ts
Description
---
- removed `useEffect` for tower offset in `BridgeNavigationButton` 
- hid sync with phone CTA if in seedless mode
- adjust/remove some tower logs
---
- closes #2430 
- closes #2427 
---
- locally:
https://github.com/user-attachments/assets/abdd0815-40b7-4b26-888d-332558ab3820
=> fix(ui): seedless UI - tower offset & sync CTA

src-tauri/src/commands.rs, src-tauri/src/internal_wallet.rs, src/components/transactions/history/List.tsx, src/hooks/wallet/useFetchTxHistory.ts, src/store/actions/walletStoreActions.ts, src/store/useBlockchainVisualisationStore.ts, src/store/useWalletStore.ts
* use clean_data_folder from wallet manager, to also change init scan flag
main issue was:
```
state
.wallet_manager
.set_view_private_key_and_spend_key(wallet.get_view_key(), wallet.get_spend_key())
.await;
```
Wallet process was starting with old keys
=> fix: importing seed words

src/components/mining/timer/MiningTime.tsx, src/components/tapplets/Tapplet.tsx, src/containers/main/Dashboard/Dashboard.tsx, src/containers/main/Dashboard/MiningView/MiningView.styles.ts, src/containers/navigation/Sidebars/BridgeNavigationButton.tsx, src/containers/navigation/Sidebars/SidebarMini.tsx, src/hooks/airdrop/stateHelpers/useAirdropPolling.ts, src/store/actions/airdropStoreActions.ts, src/store/actions/setupStoreActions.ts, src/store/consts.ts, src/store/useTappletsStore.ts
Description
---
- add check for `days` in `MiningTime` (fixes random lonesome `0` on start up in `PoolStatsTile`)
- add `TappletContainer` with updating styling for bridge section
- remove old feature flags 
---
- locally:
| before | after |
| :---: | :---: |
| ![image](https://github.com/user-attachments/assets/d7cbc3c2-fd2d-4857-881c-6b4490637b89) | <img width="231" alt="image" src="https://github.com/user-attachments/assets/fbb28f7b-ffe5-4b16-97de-8cbbe2fe8a09" /> |
| <img width="1332" alt="image" src="https://github.com/user-attachments/assets/8cd4a7da-f963-403a-b0a3-89b3b258e6cf" /> | <img width="1327" alt="image" src="https://github.com/user-attachments/assets/8bc31510-17e9-4d5b-9428-fe4f4b436a08" /> |
=> fix(ui): pool stats days | old feature flags | cleanups

src/components/transactions/history/List.tsx, src/store/actions/walletStoreActions.ts
when bridge api is not responsive, this fix prevents endless loop of api calls as we are fetching transactions inside component
=> fix: bridge api handle error on fetch

src/components/elements/inputs/Select.styles.ts, src/components/elements/inputs/Select.tsx
Description
---
dropdown styling was changed in sidebar updates and it affected the existing language dropdown
- just fixed by reverting back to original styling for that variant & setting width in the positioning wrapper
---
- closes #2461 
---
- locally:
https://github.com/user-attachments/assets/537fc1e8-501f-4074-94c0-a3bee082c1c9
---
- check that the lang dropdown styling is restored
- new history list filter dropdown still as is
=> fix(ui): language dropdown styling

src/components/wallet/sidebarWallet/SidebarWallet.tsx
Description
---
there was a misunderstanding on where/when the new sync UI should be displayed in the sidebar wallet section - this PR simply removes the `walletIsScanning` check from the sync UI condition
---
- locally:
https://github.com/user-attachments/assets/ed74f367-b210-46c9-9829-69e8a0d83825
https://github.com/user-attachments/assets/e1da1c77-d139-4be2-b156-55ac3d27895d
=> fix(ui): only check sync for syncing UI in wallet

src/store/actions/appConfigStoreActions.ts, src/store/actions/miningStoreActions.ts
Description
---
- just fixed the checks for `miningInitiated` in the CPU/GPU mining enabled toggles so that they'd start up when enabled if (any type of) mining is already initiated
---
- closes #2466 
---
- locally:
https://github.com/user-attachments/assets/c2580f1d-8966-4033-8d74-384237bd4b09
=> fix(ui): start mining on toggle

src/components/transactions/history/List.tsx
Closes #2475
Don't always append bridge transactions, do it only when `transactions` or `all activity` filter selected
=> fix: filtering bridge txs

public/locales/af/wallet.json, public/locales/cn/wallet.json, public/locales/de/wallet.json, public/locales/en/wallet.json, public/locales/fr/wallet.json, public/locales/hi/wallet.json, public/locales/id/wallet.json, public/locales/ja/wallet.json, public/locales/ko/wallet.json, public/locales/pl/wallet.json, public/locales/ru/wallet.json, public/locales/tr/wallet.json, src/components/transactions/wallet/Exchanges/exchange-button/ExchangeButton.tsx, src/components/transactions/wallet/Exchanges/exchange-button/styles.ts, src/components/wallet/components/balance/WalletBalance.tsx, src/components/wallet/sidebarWallet/SidebarWallet.tsx, src/components/wallet/sidebarWallet/styles.ts
Just a few small tweaks to the Wallet section. 
If the Available Balance is the same as the main balance, it now shows "My Balance" label. It's weird to show the same value twice if available balance and mined balance is the same. 
I also made it so the Exchange button hides itself when the History List is scrolled, this was a request from design.
=> fix(ui): hide exchange button on scroll and show my balance text

src/containers/navigation/components/MiningButtonCombined/MiningButton/MiningButton.tsx, src/containers/navigation/components/MiningButtonCombined/MiningButton/components/AnimatedBackground/AnimatedBackground.tsx, src/containers/navigation/components/MiningButtonCombined/MiningButton/components/AnimatedBackground/styles.ts, src/containers/navigation/components/MiningButtonCombined/MiningButton/styles.ts
This update adds a slight shadow to the mining button when it's not mining. So the button appears "lighter" while it's mining. This helps differentiate the 2 states so it's clearer when the mining has stopped. 
https://www.loom.com/share/7b486329ec7e41d2a0417f36ffbe910f?sid=d3128f12-66a6-4bdf-af13-2fb5874e0f41
=> fix(ui): made start mining button darker when not active

src-tauri/src/tor_adapter.rs
Description
---
Regardless of whether or not a user has installed `libevent` from their package manager, the version of `libevent-2.1.so.7` bundled with tor should be used on linux systems.  Even though both the bundled and system copy are listed as the same version, they do not provide the same symbols.  This ABI mismatch is the cause of tor failing to start, not the lack of it being installed.
Here, the linker is able to find the system-copy of `libevent-2.1.so.7`, but tor still fails to launch due to the missing symbol:
```
$ sudo find / -name libevent-2.1.so.7
/usr/lib64/libevent-2.1.so.7
$ cd ~/.cache/com.tari.universe.alpha/binaries/tor-binaries/esmeralda/14.5.1/tor
$ ldd ./tor
...
libevent-2.1.so.7 => /lib64/libevent-2.1.so.7 (0x00007f184eb91000)
...
$ ./tor
./tor: symbol lookup …
```
=> fix: always use tor-bundled `libevent-2.1.so.7` on linux

src/containers/main/Dashboard/components/VisualMode.tsx, src/hooks/app/useTauriEventsListener.ts, src/store/actions/setupStoreActions.ts, src/store/actions/uiStoreActions.ts, src/store/useUIStore.ts
Description
---
`loadTowerAnimation` was being called multiple times from `handleAppUnlocked`, causing multiple layers of the animation
**it should be fine with https://github.com/tari-project/universe/pull/2492 going in, but doesn't hurt to have a fallback in case something else triggers this action twice** 
- add store var if tower has been initialised or not before calling `loadTowerAnimation` during set up
- small cleanups in store actions & visual mode toggle
---
- closes #2491 
---
- locally:
=> fix(ui): multiple tower init

src-tauri/src/wallet_manager.rs
Description
---
Solves the issue that under linux we would have deleted a folder in `app_local_data_dir` which is different than the app_config_dir() (.local/share as opposed to .config). The fix does not solve the underlying issue that  we are trying to delete the folder but prevents the app from crashing if the folder is not there (we do nothing in that case)
---
Fixes #2487 
---
Locally withe esme
---
Change the seed words while setting the application up.
---
=> fix: seed word restoration

src/containers/floating/Settings/sections/connections/NodeTypeConfiguration.tsx
Description
---
- adjusted select wrapper styling and middleware props
---
overflow was borked:
---
- locally:
https://github.com/user-attachments/assets/840def2d-93e5-4421-a6f9-eaa8eb6ba2c7
=> fix(ui): node type select styling

src-tauri/src/gpu_miner_sha_websocket.rs
- Adjusted structure that we are expecting to parse to the content from gpu stats response
- Remove display formatting as it was obsolete
- Add log of received data that triggers only once each times that we get new parsing fail, eg.:
- Success Success Success Success => won't trigger
- Success Success Fail Success => trigger only once
- Fail Fail Fail Fail => trigger only once
- Success Fail Success Fail => trigger twice
Should fix #2534
=> fix: gpu miner stats response structure parsing error

src/components/GreenModal/styles.ts
Description
---
* Lower PaperWallet modal z-index from 9999 to 99(pin dialogs are 100)
=> fix: paper wallet covers pin dialog

src-tauri/src/gpu_miner_sha_websocket.rs, src/containers/floating/Settings/sections/pools/CpuPoolsSettings.tsx, src/containers/floating/Settings/sections/pools/GpuPoolsSettings.tsx, src/containers/navigation/components/Miner/components/CustomPowerLevels/CustomPowerLevelsDialog.tsx, src/containers/navigation/components/Miner/components/ModeSelect.tsx, src/containers/navigation/components/MiningButtonCombined/LoadingButton/LoadingButton.tsx, src/containers/navigation/components/MiningButtonCombined/MiningButton/MiningButton.tsx, src/containers/navigation/components/MiningButtonCombined/MiningButton/components/ModeDropdown/ModeDropdown.tsx, src/store/actions/appConfigStoreActions.ts, src/store/useAppConfigStore.ts, src/types/configs.ts
- Fixed mining mode ui not changing when switching to **ludicrous** mode
- Extended interface for `selected_mining_mode` to include undefined value to prevent errors
- Change how pool info and selected mining mode are retrieve from the store
- Removed commented out code
=> fix: mining mode ui states and typing

src-tauri/src/internal_wallet.rs
```rs
.map_err(|e| {
// Only display once
block_on(EventsEmitter::emit_show_keyring_dialog());
anyhow!("Failed to get tari seed from keyring: {e}")
})?
```
```log
thread 'tokio-runtime-worker' panicked at /Users/mpap/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.46.1/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```
=> fix: keyring dialog not displayed on deny

src/components/elements/dialog/Dialog.styles.ts, src/components/elements/dialog/Dialog.tsx
Description
---
- just disable transaparentBg prop if os is linux
---
`backdrop-filter` blur isn't working on linux
=> fix(ui): disable transparent bg for linux

src-tauri/src/commands.rs, src-tauri/src/configs/config_wallet.rs, src-tauri/src/internal_wallet.rs, src-tauri/src/pin/pin_manager.rs, src-tauri/src/setup/setup_manager.rs, src/components/exchanges/universal/option/InternalWalletOption.tsx, src/components/exchanges/universal/option/XCOption.tsx, src/components/security/pin/EnterPin.tsx, src/components/wallet/seedwords/SeedWords.tsx, src/containers/floating/Settings/sections/wallet/SeedWordsMarkup/useGetSeedWords.ts, src/containers/floating/security/pin/ForgotPinDialog.tsx, src/store/actions/walletStoreActions.ts
Description
---
* Before loading an owned(internal) tari wallet, validate if config wallet contains all required details. If no, try to extract all missing
* Don't remove tari wallet details from the wallet config file, when switching to external tari address. It allows us to smoothly switch to Standard Universe - no keyring prompt, easier flow
* Make it possible to get tari and monero seed before InitialWallet is even initialized
* Hide error tooltips when user cancelled keyring access or pin entering
* DIsplay errors if something else happened
=> chore: improve wallet error handling

public/locales/af/wallet.json, public/locales/cn/wallet.json, public/locales/de/wallet.json, public/locales/en/wallet.json, public/locales/fr/wallet.json, public/locales/hi/wallet.json, public/locales/id/wallet.json, public/locales/ja/wallet.json, public/locales/ko/wallet.json, public/locales/pl/wallet.json, public/locales/ru/wallet.json, public/locales/tr/wallet.json, public/locales/vi/wallet.json, src/components/wallet/components/balance/WalletBalance.tsx
Description
---
- updated the `wallet-scanning-with-progress` copy to include the block sync progress (again:D)
- fixed the rounding on the percentage (to include 1 decimal)
---
- better feedback that something _is_ happening, since wallet scanning could potentially take a long time
---
- locally:
https://github.com/user-attachments/assets/12b38160-0025-49e0-9c9c-09cff8d24e0f
=> chore(ui): add block scan to wallet progress copy

.github/workflows/ci.yml, package-lock.json, package.json, src-tauri/Cargo.lock, src/main.tsx
Description
---
this is a continuation of https://github.com/tari-project/universe/pull/2494 and a replacement for https://github.com/tari-project/universe/pull/2490 which i just closed because i got carried away with unrelated changes
- bump tauri's cargo packages 
- bump tauri's npm packages (only cli was behind)
- update the CI workflow so `tauri-cli` is not locked any more (was quite far behind - 2.4.0 vs latest 2.7.1)
- added `onRecoverableError` logging in main too 
---
- initially the motivation was just to get rid of last console error WRT tauri events but can't be sure this solves it ... so:
- keep up to date on tauri changes and bug fixes 
---
- locally, **BUT** when i tried to get a video with the last remaining listener …
=> chore: bump tauri deps and clean install

src/components/sync/Sync.tsx, src/containers/navigation/components/MiningTiles/MiningTiles.tsx, src/containers/navigation/components/MiningTiles/components/SyncData/SyncData.tsx
Description
---
- hide second line for Sync details if no `setupPhaseTitle` 
- hide `Mine directly to an exchange` CTA if on exchange specific miner
- small settings style change so there's no big gap from `SettingsGroupWrapper`'s padding when syncing isn't displayed yet
---
---
- locally:
=> fix(ui): exchange miner loading text

src/components/transactions/history/ListItem.styles.ts, src/components/wallet/components/history/styles.ts, src/components/wallet/sidebarWallet/SidebarWallet.tsx, src/components/wallet/sidebarWallet/styles.ts, src/containers/navigation/components/Wallet/ListLoadingAnimation/ListLoadingAnimation.tsx, src/containers/navigation/components/Wallet/ListLoadingAnimation/styles.ts
1. remove blur from list item hover and add a gradient instead to cover the number below the buttons. This is cleaner and looks more professional. The blur was too much.
2. There was a slight gradient mask showing through on the top of the list, this was effecting the top list item. I just removed it so the top of the list is clean.
3. Add a subtle text scale hover effect to the "Buy Tari" button.
4. The loading UI had some extra padding at the top, The loading text also had an HTML tag within it that was rendering as text. I don't think this loading UI is shown anymore, so this was missed.
=> fix(ui): minor wallet transaction ui tweaks

src-tauri/src/wallet/wallet_manager.rs
Description
---
Fixes: #2564 
After importing wallet, the scanned balance was invalid but wallet would re-validate it after around ~30 seconds. To fix it I added flat 30 seconds timeout to check balances again and change it.
---
Imported wallet and confirmed that balance was correct.
---
=> fix: refresh balance after initial scan is completed

src/components/transactions/WalletSidebarContent.tsx, src/components/transactions/send/SendForm.tsx, src/components/transactions/send/SendModal.tsx
Description
---
- set state `address` if the form value exists (like in the case of going back to review)
- also in `WalletSidebarContent.tsx` just removing the `SendModal` from the DOM if not needed so the form values clear entirely on reset without having to close the sidebar)
---
- fixes https://github.com/tari-project/universe/issues/2647
---
- locally:
switched between review with/without changes, closing entirely, adding more in a different field etc
https://github.com/user-attachments/assets/d76553c6-abfa-4739-a283-4bf88bce6179
=> fix(ui): send form | review button disabled upon going back

src-tauri/src/wallet/wallet_manager.rs
Description
---
Closes: #2655 
Fixes blocking operation done by wallet scanning which took 2 minutes and blocked shutdown.
---
Launch app and try to close app right after initial scan completed which will be indicated with these logs:
```
14:33:49 INFO  Wallet scan completed up to block height 62616
14:33:49 INFO  Initial wallet scan complete up to 62616 block height. Available balance: 10114.597741 T
```
---
=> fix: balance validation blocking shutdown

src/hooks/airdrop/utils/useHandleRequest.ts, src/hooks/exchanges/fetchExchangeContent.ts
Description
---
- get `baseUrl` from the correct store (for `handleAirdropRequest`)
- adjusted the console.warn just so we can get a better idea of what's missing
- check for the `baseUrl` for enabled too in `useFetchExchangeBranding`
---
- we use the airdrop request now for exchange content, and `handleAirdropRequest` still used `useAirdropStore` to grab the API URL - which may not be set right on startup (though `useConfigBEInMemoryStore` is)
---
- locally
=> fix: reference correct store for API URL

src/containers/navigation/SidebarNavigation.tsx, src/containers/navigation/Sidebars/Sidebar.styles.ts, src/containers/navigation/Sidebars/Sidebar.tsx
The sidebar was not animating properly when open/closed. There were some props there for an animation, but i'm taking a more simplified approach here. 
The sidebar now animates when it opens and exits. The effect is subtle but adds more visual flare as opposed to popping in and out. 
Here's a video of the animation. 
https://www.loom.com/share/c71e99aefcb9412b908e6c7b907ad77c?sid=dae3c0df-901a-4c91-b532-1bef541e5af7
=> fix(ui): add state animation to the sidebar

src-tauri/src/setup/listeners/listener_unlock_cpu_mining.rs, src-tauri/src/setup/listeners/listener_unlock_gpu_mining.rs, src-tauri/src/setup/phase_core.rs, src-tauri/src/setup/setup_manager.rs, src/store/actions/appConfigStoreActions.ts
handle_restart methods didn't have newest setup features loaded which for cpu case made it lock mining and not unlock it
=> fix: cpu mining resuming when pool toggling

src/containers/floating/XSpaceBanner/XSpaceBanner.style.ts, src/containers/floating/XSpaceBanner/XSpaceBanner.tsx
This update adjusts the XStateBanner position for when the Crew Rewards widget is minimized. 
The banner has a different position for each of the following cases:
- Crew rewards is disabled
- Crew rewards is active ( not logged in )
- Crew rewards is active ( logged in )
- Crew rewards is minimized
Loom Video of all the possible positions:
https://www.loom.com/share/0e5030c121ec4a8cbc381983bce011fb?sid=e3f29564-7928-4cae-9ed3-07dc811ed65e
=> fix(ui): xstate banner position for when the rewards widget is minimized

src/containers/main/Airdrop/sidebar/User.tsx, src/containers/main/Airdrop/sidebar/components/Avatar/Avatar.tsx, src/containers/main/Airdrop/sidebar/components/Avatar/styles.ts
When the logged in user doesn't have an avatar image, it now shows the first initial of their username along with a seed generated gradient background. This makes the generated avatar feel more complete and personalized.
=> fix(ui): add initial letter to the avatar component when image is blank

src-tauri/src/commands.rs, src-tauri/src/events.rs, src-tauri/src/events_emitter.rs, src-tauri/src/main.rs, src-tauri/src/node/node_adapter.rs, src-tauri/src/node/node_manager.rs, src-tauri/src/setup/phase_node.rs, src-tauri/src/telemetry_manager.rs, src/components/transactions/history/List.tsx, src/components/transactions/history/details/getListEntries.tsx, src/components/wallet/components/balance/WalletBalance.tsx, src/components/wallet/sidebarWallet/SidebarWallet.tsx, src/containers/floating/Settings/sections/connections/ConnectionStatus.tsx, src/containers/floating/Settings/sections/connections/Network.tsx, src/containers/floating/Settings/sections/connections/Peers.tsx, src/containers/floating/Settings/sections/experimental/DebugSettings.tsx, src/containers/main/Dashboard/MiningView/components/BlockTime.tsx, src/containers/navigation/components/MiningTiles/components/Tile/Tile.tsx, src/containers/navigation/components/VersionChip/ConnectedPulse/ConnectedPulse.tsx, src/hooks/app/useTauriEventsListener.ts, src/store/actions/index.ts, src/store/actions/miningMetricsStoreActions.ts, src/store/actions/nodeStoreActions.ts, src/store/index.ts, src/store/useMiningMetricsStore.ts, src/store/useNodeStore.ts, src/types/backend-state.ts, src/types/events-payloads.ts, src/types/invoke.d.ts
Description
---
**(+ 80% calls reduction)**
* Remote node's network status fetched once per 45secs instead of once per 10secs
* Orphan check uses global network status instead of fetching it's own once per 30sec(btw increased this to 60secs)
**(~66% calls reduction)**
- Orphan check changed to be performed once per 60secs instead of once per 30secs
- telemetry service uses already defined flag
**(~ 99% calls reduction)**
- `list_connected_peers` called on demand, not once per 10 sec
---
* Remote nodes are overloaded with grpc calls that could be optimize
Frontend updates
---
Move node related properties from `miningMetricsStore` to `nodeStore`
=> chore: remote node calls optimization

src-tauri/src/cpu_miner.rs
- Prevent passing to xmrig threads arg values below 1 and bigger then available threads
=> fix: clamp cpu cores to use between 1 and max available cores

src-tauri/src/websocket_events_manager.rs
Previously, the code attempted to decode a JWT token even if it was empty, which could lead to errors. This commit adds a check to ensure that the JWT token is not empty before attempting to decode it. This prevents unnecessary errors and ensures that the claims ID is correctly set.
=> fix: ensure jwt token is not empty before decoding

src/containers/navigation/components/MiningTiles/components/exchange-button/ExchangeButton.tsx, src/hooks/exchanges/fetchExchanges.ts
Description
---
`apiUrl` was empty when the query was initially fired, and being in a normal function there was no update once it was set, so just moved getting it to the query hook & used the value for `enabled`
---
- fixes https://github.com/tari-project/universe/issues/2790 😬 
---
- dlocally:
=> fix(ui): query checks for exchanges

src-tauri/src/telemetry_service.rs
I noticed an `if let Some(x) =` check around the tx_channel when trying to send a telemetry event. This lead me to refactor it a bit so that the tx_channel was always populated. 
I changed the looping logic around telemetry as well as removing retries, which seem unnecessary, since we will send again later.
=> fix: fix missing telemetry messages that happen before service starts

src/components/elements/dialog/Dialog.styles.ts
The z-index on the `Dialog` component being set to `1` is too low and causing issues with the stacking order. Modals should always be above everything ( except other more important modals like critical errors ).   
This PR sets the `z-index: 99` which should be high enough to prevent issues.
=> fix(ui): set dialog z-index to a higher number to fix modal stacking

src/containers/main/CrewRewards/RewardsWidget/RewardsWidget.tsx, src/containers/main/CrewRewards/RewardsWidget/styles.ts
This PR mades the "Manage your crew" expand button in the Crew Rewards widget full width. This was a request for product/design.
=> fix(ui): full width manage your crew button

src/components/elements/Avatar/styles.ts, src/containers/main/CrewRewards/RewardsWidget/sections/MainSection/segments/StatsRow/AvatarInviteButton/AvatarInviteButton.tsx, src/containers/main/CrewRewards/RewardsWidget/sections/MainSection/segments/StatsRow/AvatarInviteButton/styles.ts, src/containers/main/CrewRewards/RewardsWidget/sections/MainSection/segments/StatsRow/StatsRow.tsx, src/containers/main/CrewRewards/RewardsWidget/sections/MainSection/segments/StatsRow/styles.ts
When there was less than 3 crew members, the UI looks a little strange. This PR adds placeholder avatars that work as invite buttons when clicked. 
I also made it so when you click on a real avatar it opens the full crew rewards list view.
=> feat(ui): crew rewards invite avatar placeholder buttons

src-tauri/src/mining/gpu/manager.rs
- When user disable gpu pool and start mining / is mining it will automatically switch to glytex as its only miner that support solo mining
- If user was solo mining and enable pool mining it will automatically switch to a miner that supports pool mining and is healthy in order => LolMiner => Graxil
=> fix: handle automatically switching to proper miner when pool is enabled or disabled

src-tauri/src/mining/gpu/miners/glytex.rs, src-tauri/src/mining/gpu/miners/graxil.rs, src-tauri/src/mining/gpu/miners/lolminer.rs, src-tauri/src/process_watcher.rs
- Remove warnings for healthstatus from gpu miners | Its either healthy or unhealthy
- If we cannot fetch or send gpu status => mark it as unhealthy instead warning
- If hashrate is 0.0 => It should be marked as unhealthy
- Removed 10 seconds grace period for hash rate check to prevent producing false positive results
=> fix: miners sometimes not properly marked as unhealthy

src/containers/main/CrewRewards/RewardsWidget/sections/MainSection/segments/StatsRow/StatsRow.tsx, src/containers/main/CrewRewards/RewardsWidget/sections/MainSection/segments/StatsRow/styles.ts, src/store/useAirdropStore.ts
This PR adds the status indicator to the member avatars in the collapsed state of the crew rewards widget. 
I also added a hover effect that scales and blurs the other circles within this component when one of them is hovered, this is to draw focus to the one being interacted with. I found it was too visually confusing when hovering the middle avatar.
=> fix(ui): status indicators on crew rewards avatars

src-tauri/src/configs/config_core.rs, src-tauri/src/configs/config_mining.rs, src-tauri/src/configs/config_pools.rs, src-tauri/src/configs/config_ui.rs, src-tauri/src/configs/config_wallet.rs, src-tauri/src/internal_wallet.rs
- Added `version_counter` to each config
- If there was `version` ( i32 ) present replaced it with `version_counter` ( u32 ) | config version cannot be negative, replacement was needed as I cannot change type of that field because then the deserialization would fail 
- Added pub const's to each config representing it current expected version 
- Set `version_counter` default value as that mentioned pub const so fresh configs will not require any migration 
- Removed `was_config_migrated` field
=> fix: add version counter to each config file

src-tauri/src/internal_wallet.rs
- When initializing wallet with seed, in case there is no wallet records in config ( which means there is no references to record in keyring ), mark validation as failed instead of throwing error, which should trigger migration attempt if available and if not create new wallet
=> fix: handle wallet initialization dead end when no config record exists

src-tauri/src/node/node_adapter.rs
Probably will fix: https://nomatter.tari.com/tari/pl/gorbc5eyuj8qxq6ecepnuo6eba
From what I've investigated in core repo, some config is malformed which throws error on serialization which in returns throws 101 error in TU, to try and fix this I've added deletion of config folder on `handle_unhealthy` 
Tested by changing config.toml file and running TU app, I can see the same error as in error report and then deletion happen which looks like it fixing the issue, node running properly after
=> fix: possible malformed node config files

src/containers/main/CrewRewards/RewardsWidget/sections/CrewSection/CrewSection.tsx, src/store/useAirdropStore.ts
Updates the Crew Rewards widget to display dynamic reward values fetched from the `rewardsConfig` in the `progressData`. This ensures that the values for user rewards, days required, and friend rewards are configurable and not hardcoded. The `rewardsConfig` interface has been added to the store.
=> feat: display dynamic reward values

src/App/App.styles.ts, src/containers/main/CrewRewards/CrewRewards.tsx
The exit animation on the app is strange when closing. It also prevents the "Shutting down" ui from displaying. This PR removes the exit animation. Much cleaner exit experience. 
Bug:
https://www.loom.com/share/9c0a90191f3f43a69108ed5d003f5e8f
Fix:
https://www.loom.com/share/b60eefa1c9084d578e3eb17ff1300783
I also disabled the Crew Rewards widget when shutting down, it was appearing over it. 
Bug:
Fix:
=> fix(ui): remove the zoom out animation when exiting the app

src-tauri/binaries-versions/binaries_versions_nextnet.json, src-tauri/binaries-versions/binaries_versions_testnets.json
Description
---
Bumps `bridge` tapplet version in testnet and nextnet to `v0.2.2-pre.0`
---
We built a new release of bridge tapplet - `v0.2.2-pre.0`. It has to be tested.
---
Ran locally an the new tapplet version was downloaded and run.
```
14:55:06 INFO  Downloading binary: bridge from url: https://cdn-universe.tari.com/tari-project/wxtm-bridge-frontend/releases/download/v0.2.2-pre.0/bridge-v0.2.2-pre.0.zip                                                                              
14:55:07 INFO  Using archive destination: /Users/martinserts/Library/Caches/com.tari.universe.alpha/tapplets/bridge/esmeralda/0.2.2-pre.0/archive
14:55:07 INFO  Destination directory: /Users/martinserts/Library/Caches/com.tari.universe.alpha/tapplets/bridge/e …
```
=> chore: bump bridge tapplet version in testnet and nextnet to v0.2.2-pre.0
