src/containers/AppBackground/AppBackground.tsx
Description
---
Typo on the background type
---
---
---
---
x
=> fix: background type

.github/workflows/release.yml, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
Add release workflow with tauri updater
Having a tauri application that builds and has updater function
Mostly built in local fork.
---
---
=> ci(fix): add release workflow with tauri updater

.github/workflows/ci.yml
Description
Add a few cargo tests
Keep rust nice
Runs and fails some tests in local fork
---
---
=> ci(fix): add a few cargo tests

.github/workflows/ci.yml
Description
Install Linux dependencies for clippy
Improve clippy test
--
---
---
=> ci(fix): install Linux dep packages for clippy

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/minotari_node_adapter.rs, src-tauri/src/node_manager.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_watcher.rs, src/containers/SideBar/Miner/Miner.tsx
=> feat: add estimated earnings

.github/workflows/ci.yml, .github/workflows/release.yml
Description
Add protobuf dependencies for ci and release
Add push to release for releases
Fix CI and releases better by removing double CI builds
---
=> ci(fix): add protobuf dependencies

package-lock.json, package.json, src/containers/SideBar/Miner/components/AutoMiner.tsx, src/store/appStateStore.ts
Description
---
Implement auto mining behavior based on user activity 
---
Manually
---
Open our app, click on Auto Miner switch button and do move mouse inside app for 30 seconds
---
=> feat(UI): implement auto mining

src/containers/Dashboard/MiningView/components/BlockInfo.tsx
Description
---
Fixes the formatting & typescript errors on the BlockInfo component
The days calculation looks way off though, so please check
---
The BlockInfo component was causing the app to crash
---
Manually
---
---
x
=> fix: blockinfo formatting

src/App.tsx, src/containers/SideBar/components/Wallet.tsx, src/store/appStateStore.ts, src/store/walletStore.ts
Description
---
Fixed the formatting of the wallet balance and also added decimals
Moved the wallet state into its own store
---
When your balance gets too large, it pushes out of the container
---
Manually
---
---
x
=> fix: wallet balance formatting

src-tauri/src/binary_resolver.rs, src-tauri/src/cpu_miner.rs, src-tauri/src/download_utils.rs, src-tauri/src/main.rs, src-tauri/src/merge_mining_adapter.rs, src-tauri/src/minotari_node_adapter.rs, src-tauri/src/mm_proxy_manager.rs, src-tauri/src/node_manager.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_watcher.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs, src-tauri/src/xmrig_adapter.rs, src/App.tsx
Adds progress when downloading the applications. Probably not the cleanest but will help for now
=> fix: better download progress

src/App.tsx, src/containers/SideBar/Miner/components/ModeSelect.tsx, src/hooks/useGetStatus.ts
Description
---
---
---
---
---
=> fix(UI): fix dupe & build err

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/merge_mining_adapter.rs, src-tauri/src/minotari_node_adapter.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_killer.rs, src-tauri/src/process_watcher.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/xmrig_adapter.rs
Description
---
---
---
---
---
=> feat: kill old processes before starting

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src/App.tsx, src/containers/SideBar/components/Settings.tsx, src/types/invoke.ts
Description
---
Add button for opening logs directory
---
Add easy access to logs directory
---
Manually
---
Open settings tab and click button for opening directory
---
=> feat(ui): implemented button for opening logs directory

src-tauri/src/binary_resolver.rs, src-tauri/src/main.rs, src-tauri/src/xmrig_adapter.rs, src/App.tsx, src/containers/SideBar/components/Settings.tsx, src/hooks/useGetApplicatonsVersions.ts, src/store/useAppStatusStore.ts, src/types/app-status.ts
Description
---
Implement display for all versions of our applications
---
We want to easily see which versions are we running on
---
Manually
---
Open settings tabs and you should see all versions
---
=> feat(ui): implement display for applications versions

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/cpu_miner.rs, src-tauri/src/gpu_miner.rs, src-tauri/src/main.rs, src/containers/SideBar/components/Heading.tsx, src/containers/SideBar/components/Settings/Card.component.tsx, src/containers/SideBar/components/Settings/Settings.styles.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/store/useAppStatusStore.ts, src/types/app-status.ts
Description
---
Implement monitoring and display for cpu and gpu temperatures
---
As mining is heavy operation for hardware we want to see at least their temperatures to know if it safe to continue mining as high temperatures may cause damages
---
Manually
---
Open settings tab and you should see Hardware temperatures category
---
=> feat: show cpu gpu temperatures

src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/minotari_node_adapter.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_killer.rs
Adds more handling of xmrig summary errors
=> fix: fix summary error from xmrig

.github/workflows/release.yml
Description
Disable default debug releases
---
---
---
---
=> ci(fix): disable default debug releases

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
Description
Enable single instance feature
Stop Windows from open multiple copies of the application
Built and test on Windows locally
---
---
=> feat(windows): run only single instance

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/binary_resolver.rs, src-tauri/src/main.rs, src-tauri/src/merge_mining_adapter.rs, src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_watcher.rs, src-tauri/src/wallet_adapter.rs
Fixes the error you get when running a pre: 1.2.0-pre.0 version of esme node
=> fix: clean old db if corrupt database warning

src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/mm_proxy_adapter.rs, src-tauri/src/mm_proxy_manager.rs, src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_watcher.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs, src-tauri/src/xmrig_adapter.rs
Puts tari logs in same folder as other logs
=> fix: put tari logs in common log folder

src-tauri/src/binary_resolver.rs, src-tauri/src/main.rs
Description
---
---
---
---
---
=> feat: fix-reading-versions-from-missing-folder

index.html, package-lock.json, package.json, src/components/CharSpinner/CharSpinner.styles.ts, src/components/CharSpinner/CharSpinner.tsx, src/containers/Dashboard/MiningView/MiningView.tsx, src/containers/Dashboard/MiningView/components/Earnings.styles.ts, src/containers/Dashboard/MiningView/components/Earnings.tsx, src/containers/SideBar/components/Wallet.tsx, src/theme/tokens.ts
Description
---
---
---
- locally
https://github.com/user-attachments/assets/ceb4c05a-4891-4128-ad6f-c2c4d20799f9
---
---
=> feat(ui): counter animation

src-tauri/src/main.rs
Description
---
---
---
---
---
=> chore: reduce binaries update interval to 10 minutes

.github/workflows/ci.yml
Description
Add tauri build for prs
Testing incoming PR build with tauri
Runs in local fork
---
---
=> ci(feature): add tauri build for prs

src/containers/Dashboard/MiningView/components/BlockHeight.tsx, src/containers/Dashboard/MiningView/components/BlockTime.styles.ts, src/containers/Dashboard/MiningView/components/BlockTime.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/hooks/mining/useBalanceInfo.ts, src/hooks/mining/useBlockInfo.ts, src/hooks/mining/useVisualisation.ts, src/store/useMiningStore.ts, src/utils/calculateTimeSince.ts
Description
---
- added display block time which is reset to 0 on failure/success
- moved real block time to settings
- fixed the timer spacing, since Druk isn't monospaced and `tubular-nums` had no effect
- fixed some duplicate keys in maps
---
- resolves #89 
---
https://github.com/user-attachments/assets/a80d09fc-0e81-4928-8bc0-5d57b44e8e23
https://github.com/user-attachments/assets/f8947f25-2848-447d-8a04-2394ac3c02a4
debug info (real block time):
=> fix(ui): humanize block time

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/analytics.rs, src-tauri/src/app_config.rs, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src-tauri/src/mm_proxy_adapter.rs, src-tauri/src/mm_proxy_manager.rs, src-tauri/src/network_utils.rs, src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs
Adds anonymous analytics to help debugging. Can be switched off in app config
=> feat: add anonymous coinbase test analytics

src/containers/SideBar/components/Settings/Settings.tsx
=> chore(ui): seed words space separated

eslint.config.js
Description
---
---
---
---
---
=> fix: fixes eslint bug

src-tauri/src/main.rs, src/containers/SideBar/components/Settings/Settings.tsx, src/hooks/useGetApplicationsVersions.ts, src/store/useAppStatusStore.ts, src/types/app-status.ts
=> chore(versions): determine tari_universe version in rust

package-lock.json, package.json, public/locales/en/common.json, public/locales/en/mining-view.json, public/locales/pl/common.json, public/locales/pl/mining-view.json, src-tauri/src/main.rs, src/App.tsx, src/containers/SideBar/Miner/Miner.tsx, src/containers/SideBar/Miner/components/ModeSelect.tsx, src/containers/SideBar/Miner/components/Tile.tsx, src/containers/SideBar/Miner/styles.ts, src/hooks/mining/useMiningControls.ts, src/hooks/mining/useMiningEffects.ts, src/store/useAppStatusStore.ts, src/store/useUIStore.ts
Description
---
Adjusted state transitions and changing mode behavior
---
Issues:
-  When not mining and changing mode it would start mining
-  Mining and changing mode would cause weird state flickering's 
---
Manually
---
Play around with mining and changing mode
---
=> chore: fix state flickering when mode change

src-tauri/src/binary_resolver.rs, src-tauri/src/download_utils.rs, src-tauri/src/xmrig_adapter.rs, src/hooks/useSetUp.ts
* fixed hash verification on windows
* 3 times retry downloading files
* handle setup failure on the frontend
=> fix(setup): improve setup reliability and failure handling

src/containers/SideBar/components/Settings/Settings.tsx, src/hooks/useSetUp.ts, src/store/useAppStatusStore.ts, src/types/app-status.ts, src/utils/logger.ts
Description
---
- fixed lint errors
- disabled console and `any` rule in `logger.ts`... because it's a logger:D
---
- built locally:
=> fix: lint errors and disable in logger

public/locales/af/common.json, public/locales/af/components.json, public/locales/af/mining-view.json, public/locales/af/settings.json, public/locales/af/setup-view.json, public/locales/af/sidebar.json, public/locales/af/tribes-view.json
Description
---
Added Afrikaans locale
---
To expand the locale
---
Checked against commonly used terms
---
Test against common Afrikaans
---
=> feat: add afrikaans locale

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/hardware_monitor.rs, src-tauri/src/main.rs, src-tauri/src/notification_manager.rs, src-tauri/src/systemtray_manager.rs, src-tauri/tauri.conf.json
Description
---
Implement systray icon with informations about cpu, gpu and estimated earnings 
---
---
Manually
---
Open app and check system tray
---
=> feat: implement systray

.github/workflows/release.yml
Description
Add a branch build target with assets for testing
Make easier branch target build with assets
Builds in local fork with targeted branches
=> ci(fix): add a branch build target with assets for testing

src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/xmrig/latest_release.rs, src-tauri/src/xmrig_adapter.rs, src/hooks/mining/useMiningControls.ts, src/hooks/useSetUp.ts
Description
---
I improved the error handling process for setup and mining startup:
* When errors occur during the setup process, display a notification to the user indicating the issue and disable future mining.
* When errors occur during the mining startup process, display a notification to the user indicating the issue and stop the mining process immediately.
---------------------------------------------------
* When fetching latest version of xmrig failed or downloading latest version of xmrig after 3 retries - we use latest local version if any.
---
---
manually
---
---
=> fix(errors): handle errors for important actions

public/locales/en/setup-view.json, public/locales/pl/setup-view.json, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/progress_tracker.rs, src/containers/Dashboard/SetupView/SetupViewContainer.tsx
You can skip to 1:50
[361494469-c1ec334f-bd47-4013-914c-f3c77a6b5773.webm](https://github.com/user-attachments/assets/366b931e-df21-47ae-b9e0-5fa3d8a649af)
=> chore(ui): progress bar get stuck

public/locales/af/setup-view.json, public/locales/en/setup-view.json, public/locales/pl/setup-view.json, src-tauri/src/download_utils.rs, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/progress_tracker.rs, src-tauri/src/setup_status_event.rs, src/containers/Dashboard/SetupView/SetupView.tsx, src/containers/Dashboard/SetupView/SetupViewContainer.tsx, src/hooks/useSetUp.ts, src/store/appStateStore.ts, src/types.ts
* Added i18n params for setup title in order to display syncing progress with translations
* Removed unused code in node_adapter
* Check out Afrikaans
=> chore(i18n): add setup title params

package-lock.json, package.json, public/locales/en/setup-view.json, src/components/MoneroAddressInput/MoneroAddressInput.component.tsx, src/components/MoneroAddressInput/MoneroAddressInput.styles.tsx, src/components/elements/Button.styles.ts, src/components/elements/Button.tsx, src/components/elements/Dialog.tsx, src/components/elements/Select.tsx, src/components/elements/inputs/Input.styles.ts, src/containers/Error/ErrorSnackbar.tsx, src/containers/SideBar/components/Settings/AppVersions.tsx, src/containers/SideBar/components/Settings/Card.component.tsx, src/containers/SideBar/components/Settings/ResetSettingsButton.tsx, src/containers/SideBar/components/Settings/Settings.styles.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/containers/SideBar/styles.ts, src/hooks/helpers/useClickOutside.ts
Description
---
- removed hover state from wallet card
- fixed up font sizing and some layout issues in settings
* added size prop to button component
- bumped outdated deps
- updated Dialog component to cater for nested items
---
had feedback:
- if you hover over the credit card it expands
- maybe just check some of the text sizes on the settings page as well?
also was annoyed at nested dialog click-out closing the settings :D
=> fix(ui): fix up styling

src/containers/Airdrop/AirdropPermission/AirdropPermission.tsx, src/containers/Airdrop/AirdropPermissionSettings/AirdropPermissionSettings.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/store/useUIStore.ts
* Integrates telemetry setting toggle
* Sets default to false (should be false in the BE as default too if we have any defaults)
* Removes old telemetry toggle
https://www.loom.com/share/145f8ec3cbba48ffac409c760eb90307
=> feat: integrates telemetry toggle

src-tauri/src/app_config.rs, src-tauri/src/main.rs, src/containers/SideBar/Miner/Miner.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/types/app-status.ts
Add controls in settings to enabling cpu and gpu mining separately. It's not 100% though
=> feat: add separate mining enable for cpu and gpu

src/containers/SideBar/components/Settings/Settings.tsx
=> fix: lint error in settings

src-tauri/src/app_config.rs, src-tauri/src/gpu_miner.rs, src-tauri/src/gpu_miner_adapter.rs, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs
=> feat: add eco mode for gpus

public/locales/en/settings.json, public/locales/pl/settings.json, src/containers/SideBar/components/Settings/ResetSettingsButton.tsx
[Screencast from 05.09.2024 19:05:00.webm](https://github.com/user-attachments/assets/605b37c2-f0be-4e99-a244-35969da78c26)
=> chore(ui): add translations & improve ui for reset settings

index.html
Description
---
- just set the default, start, and end colour on the animation init
---
- resolves #391 
---
_waiting to win a block for a success screenshot....._
=> chore(ui): update visual colours

public/locales/en/settings.json, src/components/MoneroAddressInput/MoneroAddressInput.styles.tsx, src/components/elements/Tabs.styles.ts, src/components/elements/Tabs.tsx, src/containers/SideBar/components/Settings/DebugSettings.tsx, src/containers/SideBar/components/Settings/HardwareStatus.tsx, src/containers/SideBar/components/Settings/LogsSettings.tsx, src/containers/SideBar/components/Settings/Settings.styles.tsx, src/containers/SideBar/components/Settings/Settings.tsx, src/theme/tokens.ts
Description
---
Adds tabs to the settings popup and splits it into General and Experimental
---
Simplify the settings page
---
Manually
---
---
x
=> feat(ui): settings tabs

src-tauri/src/node_adapter.rs, src/containers/Dashboard/MiningView/components/BlockHeightAccent.styles.ts, src/containers/Dashboard/MiningView/components/BlockHeightAccent.tsx, src/containers/Dashboard/MiningView/components/BlockTime.styles.ts, src/containers/Dashboard/MiningView/components/BlockTime.tsx, src/hooks/mining/useBalanceChanges.ts, src/hooks/mining/useMiningControls.ts, src/hooks/mining/useVisualisation.ts, src/hooks/useSetUp.ts
Description
---
- added block time days and hours back (if present)
- check if mining in `useVisualisation` in case you've stopped mining once the countdown for success/fail check has started
---
- resolves #135 
---
https://github.com/user-attachments/assets/63c61a6c-f392-4ee4-9bb0-621b68c81b0b
=> fix(ui): animation stop

src-tauri/src/app_config.rs, src-tauri/src/main.rs, src/hooks/useSetUp.ts, src/types/invoke.ts
Screencast is a bit laggy, sorry for my computer 
[Screencast from 10.09.2024 16:12:46.webm](https://github.com/user-attachments/assets/d83258a1-8f24-4c90-844f-13f140720da8)
=> chore(automining): start mining right after app setup

package-lock.json, src-tauri/src/main.rs, src-tauri/src/node_manager.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/process_adapter.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/wallet_manager.rs
Changed to stop services manually, and then delete the folders afterwards, excluding EBWebView
=> fix: fix reset on windows

src/components/CharSpinner/CharSpinner.styles.ts, src/containers/SideBar/components/Wallet.styles.ts, src/containers/SideBar/components/Wallet.tsx, src/containers/SideBar/styles.ts
I also adjusted styles according to figma
=> chore(ui): toggle wallet balance visibility

src-tauri/src/app_in_memory_config.rs
New API url with x-forwarded-for
=> fix: Set the new api url

package-lock.json, package.json
Description
---
- only show display block height if greater than 0
- bump outdated deps
---
- resolves #417 
---
- locally:
https://github.com/user-attachments/assets/4a9d83e7-c213-468e-9ad1-3dd35e57e913
=> fix(ui): hide display block height until it's higher than 0

src/hooks/useVersions.ts
- change update check interval from an hour to 5 minutes
=> chore: update app version checker interval time

index.html, src/App.tsx, src/hooks/useLighting.ts
- remove sun position lighting update
=> fix: don't use useLighting

src/hooks/mining/useVisualisation.ts, src/visuals.ts
- check that the glApp animation status matches our mining state
=> fix: sync animation status with mining state

src-tauri/src/p2pool_adapter.rs
Description
---
P2pool adapter had missing to set the TARI_NETWORK env var that caused to let p2pool start always using esmeralda network.
---
---
---
---
=> fix: added missing env var to p2pool adapter

src/containers/Airdrop/AirdropLogin/UserInfo/DownloadReferralModal/styles.ts, src/hooks/airdrop/stateHelpers/useGetAirdropUserDetails.ts
- check if `user` exists to prevent crash in `useGetAirdropUserDetails`
- update `motion` => `m` from `framer-motion` in download referral modal styles
=> fix: user id check

.github/workflows/release.yml
Description
Create a daily build for testing
=> chore(ci): add daily builds as beta

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/en/settings.json, public/locales/pl/settings.json, public/locales/tr/settings.json, src-tauri/src/binary_resolver.rs, src-tauri/src/hardware_monitor.rs, src-tauri/src/main.rs, src/containers/SideBar/components/Settings/ResetSettingsButton.tsx, src/types/invoke.ts
=> chore(reset): allow user not to reset wallet data

.github/workflows/release.yml, scripts/check-get-yq.sh
Description
fix beta sub version
add yq installer for linux
=> chore(ci): fix beta sub version, add yq installer for linux

public/locales/af/settings.json, public/locales/af/sidebar.json, public/locales/cn/settings.json, public/locales/cn/sidebar.json, public/locales/en/settings.json, public/locales/en/sidebar.json, public/locales/pl/settings.json, public/locales/pl/sidebar.json, public/locales/tr/settings.json, public/locales/tr/sidebar.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs, src/containers/Dashboard/MiningView/components/BlockTime.tsx, src/containers/SideBar/SideBar.tsx, src/containers/SideBar/components/LostConnectionAlert.tsx, src/containers/SideBar/components/Settings/DebugSettings.tsx, src/containers/SideBar/components/Settings/Settings.styles.tsx, src/store/useMiningStore.ts, src/types/app-status.ts
* We wait additional 30sec for the response from peers
* We display alert below the mining button, pasue animation and hide block timer
[Screencast from 18.09.2024 17:37:28.webm](https://github.com/user-attachments/assets/4988a6b6-5a45-4e62-ae90-35188e9591be)
=> fix(connection): check connection with peers & handle issues in ui

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/log4rs_sample.yml, src-tauri/src/gpu_miner_adapter.rs, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/process_utils.rs, src-tauri/src/xmrig_adapter.rs, src-tauri/tauri.conf.json
Fixes the infinite status loop
=> fix: hotfix

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/en/settings.json, public/locales/pl/settings.json, public/locales/tr/settings.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/app_config.rs, src-tauri/src/binary_resolver.rs, src-tauri/src/main.rs, src/App.tsx, src/containers/Settings/components/LanguageDropdown.tsx, src/containers/Settings/sections/general/LanguageSettings.tsx, src/hooks/useLanguageResolver.ts, src/i18initializer.ts, src/store/useAppConfigStore.ts, src/types/app-status.ts, src/types/invoke.ts
Resolves: #484 #408 
Implemented:
- Detection of operating system language
- Persisting selected language when app close
How language detection behaves:
When user start app for the first time we will detect and set language to the one of operating system
After that Language will be always set to the one selected by user in settings
=> feat: detect system locale

.github/workflows/release.yml
Description
Fix beta targets envs with diff autoupdate URL
Add a little debugging for beta builds
=> chore(ci): fix beta targets envs with diff autoupdate URL

.github/workflows/release.yml
Description
Add envs for beta telemetry
Minor merge of release env steps
=> chore(ci): add envs for beta telemetry, minor merge of release env steps

.github/workflows/release.yml
Description
Fix double beta for tauri.bundle.identifier
=> chore(ci): fix double beta for tauri.bundle.identifier

.github/workflows/release.yml
Description
Copy telemetry envs into build step
=> chore(ci): copy telemetry envs into build step

src/containers/SideBar/Miner/Miner.tsx, src/containers/SideBar/SideBar.tsx, src/containers/SideBar/styles.ts
Description
---
refactored sidebar overflow styling because the gem box broke the layout on the smaller screensize
https://github.com/user-attachments/assets/3e6b61a4-9720-4ab3-8ae8-b07d9e764c00
=> fix(ui): sidebar overflow

.github/workflows/release.yml
=> ci: remove space

public/locales/en/airdrop.json
=> fix(ui): removed excessive exclamation points from airdrop modal text

src/containers/Settings/components/LanguageDropdown.tsx, src/i18initializer.ts, src/store/useAppConfigStore.ts
- Added missing `cn` case for Chinese language in resolveI18nLanguage method
- Integrated whole of `changeLanguage` method to `setApplicationLanguage` in `appConfigStore`
- Added fallback to `setApplicationLanguage` when rust invoke results in error
=> fix: improve language resolving and changing

src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/app_config.rs, src-tauri/src/binaries/adapter_tor.rs, src-tauri/src/binaries/binaries_list.rs, src-tauri/src/binaries/binaries_manager.rs, src-tauri/src/binaries/binaries_resolver.rs, src-tauri/src/binaries/mod.rs, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs, src-tauri/src/tor_adapter.rs, src-tauri/src/tor_manager.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs, src-tauri/tauri.conf.json, src/containers/CriticalErrorDialog/CriticalErrorDialog.tsx
Enables tor on windows by default
=> feat: enable tor on windows by default

.github/workflows/release.yml
Description
Use beta-icons for beta
=> chore(ci): use beta-icons for beta

public/locales/en/airdrop.json, src/containers/Airdrop/AirdropGiftTracker/components/Claimmodal/ClaimModal.tsx, src/store/useAirdropStore.ts
=> fix(ui): airdrop updated claim gems modal copy

src-tauri/src/gpu_miner.rs
Description
---
- remove unused fn (was it meant to be used?)
---
- clippy failing
=> chore: fix test lints

src/components/CharSpinner/CharSpinner.styles.ts
Description
---
- just used `DrukWide` in the earnings animation text
=> fix(ui): use correct font family for reward

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/en/settings.json, public/locales/hi/settings.json, public/locales/id/settings.json, public/locales/ja/settings.json, public/locales/ko/settings.json, public/locales/pl/settings.json, public/locales/ru/settings.json, public/locales/tr/settings.json, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src/containers/Settings/sections/wallet/SeedWordsMarkup/SeedWordsEdit.tsx, src/containers/Settings/sections/wallet/SeedWordsMarkup/SeedWordsMarkup.tsx, src/containers/Settings/sections/wallet/SeedWordsMarkup/SeedWordsView.tsx, src/store/useWalletStore.ts, src/types/invoke.ts
* This action requires restart. We handle copied seed phrase with spaces, commas, commas with spaces, new lines, untrimmed.
* Fixed issue with redundant seed words hook
=> feat(wallet): import seed words

src-tauri/Cargo.lock, src-tauri/src/main.rs, src/utils/shared-logger.ts
Description
---
- remove captureStackTrace & trace arg from `log_web_message`
=> fix: remove captureStackTrace

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/p2pool/models.rs, src-tauri/src/p2pool/stats_client.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/tor_manager.rs, src/containers/Settings/sections/experimental/P2poolStatsMarkup.tsx, src/store/useP2poolStatsStore.ts, src/types/app-status.ts
Adds more UI in experimental settings for p2pool. Requires an updated p2pool version to test.
=> feat: add more detail to p2pool interface

src-tauri/src/cpu_miner.rs, src-tauri/src/github/mod.rs, src-tauri/src/gpu_miner_adapter.rs, src-tauri/src/hardware_monitor.rs, src-tauri/src/main.rs, src-tauri/src/mm_proxy_adapter.rs, src-tauri/src/node_adapter.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/process_watcher.rs, src-tauri/src/tor_adapter.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/xmrig_adapter.rs
Description
---
Remove redundant imports and other lints errors.
---
Fix CI lints.
---
run `cargo lints clippy --all-targets --all-features ` and also `cargo fmt --all -- --check`
---
same as above.
---
=> fix: lints errors

package-lock.json, package.json, src/containers/Settings/sections/experimental/DebugSettings.tsx
Description
---
- just bumped outdated deps (no breaking changes)
- made sure the peers keys are unique (noticed from a sentry error)
=> chore: update deps fix small sentry err

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/internal_wallet.rs
Description
---
Make the paper wallet passphrases 5 words form the english mnemonic set. 
---
The passphrases were hard to enter
---
Manually
Waiting for confirmation it works from the mobile team.
=> feat: make paper wallet passphrases more friendly

src-tauri/Cargo.toml, src-tauri/src/binaries/adapter_tor.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/xmrig_adapter.rs
Uses dynamic ports where we were using fixed ports.
This should make running beta and production versions at the same time better.
Also upgrades tor
=> fix: use dynamic ports instead of fixed for wallet and upgrade tor

src/AppWrapper.tsx
Description
---
- don't init sentry in dev
=> chore: disable sentry on local dev

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/de/settings.json, public/locales/en/settings.json, public/locales/fr/settings.json, public/locales/hi/settings.json, public/locales/id/settings.json, public/locales/ja/settings.json, public/locales/ko/settings.json, public/locales/pl/settings.json, public/locales/ru/settings.json, public/locales/tr/settings.json, src-tauri/src/app_config.rs, src-tauri/src/main.rs, src/containers/Settings/sections/experimental/ExperimentalSettings.tsx, src/containers/Settings/sections/experimental/MonerodMarkup/MonerodMarkup.styles.ts, src/containers/Settings/sections/experimental/MonerodMarkup/MonerodMarkup.tsx, src/containers/Settings/sections/experimental/MonerodMarkup/index.ts, src/store/useAppConfigStore.ts, src/types/app-status.ts, src/types/invoke.ts
=> feat(settings): monerod nodes settings

.github/workflows/release.yml, package.json, vite.config.ts
fix releases for sentry:
- add `max_old_space_size` to release.yml
- add build.sourcemaps back to vite.config
- add more specific config for the sentry plugin souremap config
=> fix: release and build workflow for sentry

src-tauri/Cargo.toml, src-tauri/src/app_config.rs, src-tauri/src/main.rs, src/store/types.ts, src/store/useAppConfigStore.ts, src/types/app-status.ts, src/types/invoke.ts
Description
---
previously had the wrong default value in `app_config` also had the wrong item when creating the config
- renamed the field so there's no change of the previous value messing up new builds
- also made sure that everywhere it's set to a default value is the correct value
---
- locally
---
- ensure the correct default value is used on a new build
=> fix: app_config default values

src/containers/Settings/SettingsModal.tsx, src/containers/Settings/components/Navigation.tsx, src/containers/Settings/components/ThemeSelector.tsx, src/containers/Settings/sections/experimental/ExperimentalWarning.tsx, src/containers/Settings/sections/experimental/TempSettings.tsx, src/containers/Settings/sections/general/GeneralSettings.tsx, src/containers/Settings/sections/general/ThemeSettings.tsx, src/hooks/helpers/useDetectMode.ts, src/store/useAppConfigStore.ts, src/store/useUIStore.ts, src/types/app-status.ts
Description
---
- remove `TempSettings` -> moved settings that were there into general
- remove `very_experimental` tab and display logic
- add check for esme
=> fix: move settings

src-tauri/src/app_config.rs, src/store/useAppConfigStore.ts
Description
---
Defaults the feature flag to true
---
Sharing the love
---
Producing a build for QA to test
---
Share it
---
=> feat: enable reward sharing and custom power levels

package-lock.json, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/main.rs, src-tauri/src/systemtray_manager.rs
Removes slow call to gpu and cpu hardware properties. This was taking upwards of 6 seconds
=> fix: remove slow cpu and gpu usage calc

.updater/latest.json
Description
---
---
---
---
---
=> chore: revert autoupdate of 0.6.0

src-tauri/src/binaries/binaries_list.rs, src-tauri/src/external_dependencies.rs, src-tauri/src/hardware/cpu_readers/mod.rs, src-tauri/src/hardware/gpu_readers/mod.rs, src-tauri/src/hardware/hardware_status_monitor.rs, src-tauri/src/hardware_monitor.rs, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src-tauri/src/node_manager.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/systemtray_manager.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/user_listener.rs, src-tauri/src/utils/logging_utils.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs, src/containers/floating/Settings/sections/mining/GpuDevices.tsx
Description
Fixes `TypeError: undefined is not an object (evaluating 'gpuDevices.length')` on behalf of @metalaureate 
---
Locally
Locally go to Miner - Settings
---
=> fix: hotfix gpudevices.length

src/containers/main/SideBar/Miner/components/CustomPowerLevelsDialog.tsx
* Adds % to the thumb
* Fixes core and thread amount description on component open
=> fix: minor custom power levels slider

.github/workflows/lint.yml, package-lock.json, package.json, src-tauri/Cargo.toml, src-tauri/lints.toml
Description
---
Enforce good toml files and provide the tooling to do it
---
Toml keeps flip flopping based on peoples editor settings
=> chore: taplo for toml

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
=> chore(release): v0.6.17

src-tauri/Cargo.toml, src/containers/main/SideBar/Miner/components/CustomPowerLevels/CustomPowerLevelsDialog.tsx
Added proper value for custom mode in frontend logic
=> fix: custom-mode-cpu-values

src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json
Updates GPU mining to fix a bug in the slow miner
=> feat: update gpu miner

.updater/latest.json, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/process_watcher.rs, src-tauri/tauri.conf.json
Description
---
Onward and upward!
=> chore: version bump v0.8.2

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
Couldn't reproduce it on my machine, but from what I've read this package should fix the issue, need someone to test it who can reproduce this bug
=> fix: mac-app-not-opening

src-tauri/src/commands.rs
Description
---
- reference `ExternalDependencies` directly
=> fix: reference `ExternalDependencies` directly

CHANGELOG.md
Description
Updated release notes
release notes
locally
Notes have to be in root main on prod build. Then go to Settings and open Release Notes.
---
=> chore: release notes update

CHANGELOG.md
Description
For real this time
Release notes
Locally
Settings
---
=> chore: release notes

CHANGELOG.md
Description
Clear out old release note dummy data
Forgot to clear out old data
---
---
---
=> chore: clear out dummy release note data

src-tauri/Cargo.toml, src-tauri/src/commands.rs, src-tauri/src/gpu_miner.rs, src-tauri/src/hardware/hardware_status_monitor.rs, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/utils/shutdown_utils.rs
- Handle extra case for wallet creation when no data is present on machine
- Fixed prolonged shutdowns sequences at the end of setup
- Removed unnecessary thread spawn
- Fixed `gpu_detection` and `gpu_status` generation
------------
- Try copy or show seed words | play around with deleting wallet_config.json
- For closing sequence => Close app around 85% or around time when we enter main app view
=> fix: v2 issues

src/containers/floating/Settings/SettingsModal.tsx, src/containers/floating/Settings/components/Card.component.tsx, src/containers/floating/Settings/components/Settings.styles.tsx, src/containers/floating/Settings/sections/p2p/P2PConnectionData.tsx, src/containers/floating/Settings/sections/p2p/P2PoolStats.styles.ts, src/containers/floating/Settings/sections/p2p/P2PoolStats.tsx, src/containers/floating/Settings/sections/p2p/PeerTable.tsx, src/containers/floating/Settings/sections/p2p/PoolMiningSettings.tsx, src/containers/main/SideBar/Miner/components/Tile.tsx, src/store/useAirdropStore.ts, src/types/app-status.ts, src/utils/getTimeAgo.ts, src/utils/truncateString.ts
Description
---
- just some light styling updates on P2P stats
---
- resolves https://github.com/tari-project/universe/issues/1185
---
- locally:
https://github.com/user-attachments/assets/389651ee-974c-40d1-9f89-9f5b900b4689
=> chore: p2p stats UI updates

src/containers/floating/Settings/sections/p2p/P2PConnectionData.tsx, src/containers/floating/Settings/sections/p2p/P2PoolStats.tsx, src/store/useP2poolStatsStore.ts
fixes p2p stats display checking `null` store state
=> fix: opt chaining and split out the partials

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json, src/containers/floating/Settings/sections/p2p/P2PConnectionData.tsx, src/containers/floating/Settings/sections/p2p/P2PoolStats.tsx, src/store/useP2poolStatsStore.ts
=> chore: version bump 0.8.7

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/main.rs, src-tauri/tauri.conf.json
=> chore: hotfix v0.8.8

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
Description
---
Onwards and upwards!
=> chore: version bump to 0.8.9

.updater/latest.json, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
Description
---
Onwards and upwards!
=> chore: version bump 0.8.11

.updater/latest.json, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
The one that is purely a version bump. No changes.
Description
---
Onwards and upwards. Kinda. 🤪
=> chore: version bump 0.8.16

src-tauri/tauri.conf.json
Description
---
Test build for all the artifacts.
=> chore: build everything

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
Moving up, we hope
=> chore: version bump 0.8.17

.github/workflows/release.yml
=> chore: ci build fixes

.github/workflows/release.yml, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
=> chore: tauri v2 ci fixes

.github/workflows/release.yml, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
One last time with gumption
=> chore: ci fixes for v2

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
Another empty one
=> chore: version bump 0.8.21

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
=> chore: empty version bump

.github/workflows/release.yml, .gitignore
Description
Formatting improvements
Ignore auto update
Reduce PR noise including the auto-update
Builds locally in fork
=> chore(ci): formatting improvements and auto update ignore

src-tauri/src/updates_manager.rs
Description
---
Restart was triggered too early when auto update installed
=> fix: auto updates infinite loop

.github/workflows/release.yml, .gitignore, .updater/alpha-latest.json, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/p2pool/models.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/updates_manager.rs, src-tauri/tauri.conf.json
Description
---
fix auto-update loop
=> chore: update version 0.8.23

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
empty version for update testing
=> chore: version bump 0.8.24

.updater/alpha-latest.json, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/node_manager.rs, src-tauri/tauri.conf.json, src/App/AppWrapper.tsx
Description
---
Less crash mo' good
=> chore: version bump 0.8.25

.github/workflows/release.yml
Little update to include the version in the title.
Closes: https://github.com/tari-project/universe/issues/1274
=> feat: add TU version to the app title

.github/workflows/release.yml
Description
Fix typo for version in title, adding src folder is not needed
=> chore(ci): fix typo for version in title

.github/workflows/release.yml, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
With feeling this time!
=> chore: version bump 0.8.27

.github/workflows/release.yml
Description
Add AIRDROP_WEBSOCKET envs in CI
=> chore(ci): add AIRDROP_WEBSOCKET envs

CHANGELOG.md
Description
Release notes
---
Locally
Merge and test
---
=> chore: release notes 0.8.25

src-tauri/src/telemetry_manager.rs
=> feat: add operating system to telemetry data

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json, src/containers/floating/Settings/sections/p2p/PoolMiningSettings.tsx, src/store/useUIStore.ts
=> chore: version bump 0.8.29

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/binaries/binaries_manager.rs, src-tauri/src/commands.rs, src-tauri/src/gpu_miner.rs, src-tauri/src/gpu_miner_adapter.rs, src-tauri/src/main.rs, src-tauri/src/node_adapter.rs, src-tauri/src/node_manager.rs, src-tauri/src/process_watcher.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs, src-tauri/tauri.conf.json, src/hooks/app/useSystemTray.ts
=> chore: version bump 0.8.32

src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/p2pool_adapter.rs
=> feat: add random squads to p2pool

CHANGELOG.md
Description
Release notes 0.8.42
=> chore: release notes 0.8.42

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
Recover from previous botched version of release
=> chore(release): version 0.8.44

src/App/App.styles.ts, src/App/App.tsx, src/containers/main/Dashboard/Dashboard.tsx, src/containers/main/Dashboard/MiningView/MiningView.styles.ts, src/containers/main/Dashboard/MiningView/MiningView.tsx, src/containers/main/Dashboard/MiningView/components/Ruler.tsx
Just cleaning up some of the intro animations so they flow more smoothly. This happens between the splash screen -> setup screen & setup screen -> dashboard. 
https://github.com/user-attachments/assets/c0702db3-1f3b-4ca2-ae8f-82b438235b4f
https://github.com/user-attachments/assets/ed164048-4b5f-45c4-a2fb-fc2e5f7d1bae
=> fix(ui): intro animation optimization for main app sections

CHANGELOG.md
=> chore: release notes 0.8.44

src-tauri/src/mm_proxy_adapter.rs
Description
---
Fixed merge mining proxy health check message.
---
The wrong message was supplied with a health check failure and printed in the log files.
---
CI
---
Code review
---
=> fix: fix merge mining proxy health check message

public/locales/en/airdrop.json
Small copy update for the Airdrop login card in the sidebar
=> fix(ui): airdrop join copy update

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/airdrop.rs, src-tauri/src/app_config.rs, src-tauri/src/app_in_memory_config.rs, src-tauri/src/commands.rs, src-tauri/src/feedback.rs, src-tauri/src/main.rs, src-tauri/src/mm_proxy_manager.rs, src-tauri/src/telemetry_manager.rs, src-tauri/tauri.conf.json, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedOut/LoggedOut.tsx, src/hooks/airdrop/stateHelpers/useAirdropTokensRefresh.ts, src/store/useAirdropStore.ts, src/types/invoke.ts
=> chore(release): version 0.8.49

CHANGELOG.md
=> chore: release notes 0.8.46

.github/workflows/release.yml, CHANGELOG.md, package-lock.json, package.json, public/locales/en/airdrop.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json, src/App/App.tsx, src/containers/floating/Settings/sections/airdrop/ApplyInviteCode.tsx, src/containers/main/Airdrop/AirdropGiftTracker/AirdropGiftTracker.tsx, src/containers/main/Airdrop/AirdropGiftTracker/components/Gems/styles.ts, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/UserInfo/UserInfo.tsx, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedIn/segments/UserInfo/styles.ts, src/containers/main/Airdrop/AirdropGiftTracker/sections/LoggedOut/LoggedOut.tsx, src/hooks/airdrop/stateHelpers/useAirdropUserPointsListener.ts, src/hooks/airdrop/utils/useAvatarGradient.ts, src/hooks/airdrop/ws/useHandleWsUserIdEvent.ts, src/hooks/app/useSetUp.ts, src/store/useAirdropStore.ts, src/types/ws.ts
=> chore(release): version 0.8.50

CHANGELOG.md
=> chore: release notes 0.8.50

src-tauri/src/process_watcher.rs
Came across a case where P2pool would not start and it turned out that if the process crashes (or exits) during the expected startup time, then it doesn't log the error properly.
In this case, the process was corrupt from download, so maybe there's another weird edge case here
=> fix: add better handling of exit codes

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/main.rs, src-tauri/src/node_manager.rs, src-tauri/src/process_watcher.rs, src-tauri/tauri.conf.json, src/App/App.tsx, src/hooks/app/useSetUp.ts, src/store/appStateStore.ts, src/store/useAirdropStore.ts, src/types/invoke.ts
=> chore(release): version bump to 0.8.51

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
=> chore(release): version 0.8.52

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Description
---
A version correction as it should have been bump to 0.9.0 for rest.
=> chore: version bump 0.9.0

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/p2pool_adapter.rs, src-tauri/tauri.conf.json
=> chore(release): v0.9.1

docs/sleep_mode/sleep_mode.md
Description
---
Add findings from testing node's recovery from sleep mode. 
---
This area is still not yet well understood and could cause potential bugs.
=> docs: add docs for sleep mode while mining

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/p2pool_adapter.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/xmrig_adapter.rs, src-tauri/tauri.conf.json
=> chore(release): version 0.9.2

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/p2pool_adapter.rs, src-tauri/tauri.conf.json
=> chore(release): version bump to 0.9.5

CHANGELOG.md
Description
Release notes for 0.9.5
=> chore: release notes 0.9.5

CHANGELOG.md
=> chore: fix release notes 0.9.6

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/commands.rs, src-tauri/src/cpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/xmrig/http_api/models.rs, src-tauri/src/xmrig_adapter.rs, src-tauri/tauri.conf.json
=> chore(release): v0.9.802

.updater/latest.json, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json
=> chore(release): version 0.9.805

CHANGELOG.md, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/node_adapter.rs, src-tauri/tauri.conf.json
=> chore(release): v0.9.806

.updater/alpha-latest.json, .updater/latest.json, src-tauri/src/app_config.rs, src/components/elements/inputs/RadioButton.styles.ts, src/components/elements/inputs/RadioButton.tsx
=> Release 0.9.809 1

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/auto_launcher.rs, src-tauri/src/main.rs, src-tauri/tauri.conf.json
=> chore(release): version v0.9.811

CHANGELOG.md
=> chore: release notes 0.9.11

knip.ts, src/containers/floating/Settings/sections/mining/GpuEngine.tsx, src/containers/main/SideBar/Miner/components/CustomPowerLevels/CustomPowerLevelsDialog.tsx, src/store/useMiningStore.ts
Description
---
- just added optional chaining to the max threads fields
- removed reference to `framer-motion`, used `motion/react-m`
- updated knip config to error on 'unlisted dependencies' instead of just warning
=> fix: custom power dialog crash

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
=> chore(release): hotfix v0.9.814

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
=> chore(release): hotfix v0.9.815

.github/workflows/release.yml, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
=> chore(release): version 0.9.817

public/locales/af/wallet.json, public/locales/cn/wallet.json, public/locales/de/wallet.json, public/locales/en/wallet.json, public/locales/fr/wallet.json, public/locales/hi/wallet.json, public/locales/id/wallet.json, public/locales/ja/wallet.json, public/locales/ko/wallet.json, public/locales/pl/wallet.json, public/locales/ru/wallet.json, public/locales/tr/wallet.json, src-tauri/binaries_versions_esmeralda.json, src/components/Tabs/TabContent.tsx, src/components/Tabs/TabNav.tsx, src/components/Tabs/types.ts, src/components/transactions/WalletSidebarContent.tsx, src/components/transactions/history/HistoryList.tsx, src/components/transactions/history/HoveredItem.tsx, src/components/transactions/history/ListItem.tsx, src/components/transactions/send/Confirmation.tsx, src/components/transactions/send/Send.tsx, src/components/wallet/Address.tsx, src/containers/main/SidebarNavigation/Sidebars/Navigation.tsx, src/containers/main/SidebarNavigation/Sidebars/SidebarMiner.tsx
Description
---
- added translation keys + missing deps
=> chore(ui): translation keys

CHANGELOG.md
=> chore: release notes 0.9.817

src/components/Tabs/TabNav.tsx, src/components/transactions/WalletSidebarContent.styles.ts, src/components/transactions/history/HistoryList.tsx, src/components/transactions/history/TxHistory.styles.ts, src/components/transactions/send/Confirmation.tsx, src/components/transactions/send/FormField.tsx, src/components/transactions/send/Send.styles.ts, src/components/transactions/send/Send.tsx, src/components/transactions/send/types.ts, src/components/wallet/Address.style.ts, src/containers/main/SidebarNavigation/SidebarNavigation.styles.ts, src/containers/main/SidebarNavigation/SidebarNavigation.tsx, src/containers/main/SidebarNavigation/Sidebars/SidebarMiner.styles.ts, src/containers/main/SidebarNavigation/Sidebars/SidebarMiner.tsx, src/containers/main/SidebarNavigation/Sidebars/SidebarWallet.tsx, src/containers/main/SidebarNavigation/components/Miner/styles.ts
Description
---
- clean up sidebar padding 
- split out form fields
=> fix(ui): clean up weird padding | split out form fields

.github/workflows/release.yml, eslint.config.js, package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json, src/hooks/airdrop/useWebsocket.ts
=> chore(release): version 0.9.819

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json, src/store/actions/appConfigStoreActions.ts
=> chore(release): version 0.9.821

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
=> chore(release): version 0.9.823

src-tauri/src/spend_wallet_adapter.rs
Description
---
Update spend wallet recovery flags to use environment variable for seed
words
=> feat: env var for seed words when recovery

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/p2pool_adapter.rs, src-tauri/tauri.conf.json
=> chore(release): hotfix v0.9.827

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/p2pool_adapter.rs, src-tauri/tauri.conf.json
Description
---
onward and upward
=> chore(release): hotfix v0.9.828

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/p2pool_adapter.rs, src-tauri/tauri.conf.json
Return to 3 squads
We need to go backwards to go forwards
=> chore(release): v0.9.829

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
=> chore(release): v0.9.830

src/hooks/app/useSetUp.ts
Description
---
we no longer need a lot of the old stuff that was left in useSetup so cleaned it up
=> refactor: remove unnecessary items from useSetUp

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src-tauri/src/mm_proxy_adapter.rs, src-tauri/src/mm_proxy_manager.rs, src-tauri/src/node_adapter.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/process_adapter.rs, src-tauri/src/progress_tracker.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/tor_adapter.rs, src-tauri/src/tor_control_client.rs, src-tauri/src/tor_manager.rs, src-tauri/tauri.conf.json, src/hooks/app/useSetUp.ts
Intended to be rolled as a hotfix
* Added tor control port monitor, cherry picked from main branch.
* Added better mmproxy health check for `wait_ready`, previously this would just wait for 20 seconds.
* Tried to code some front end fixes for setup getting stuck and not processing events
=> fix: better tor and mmproxy health monitoring and frontend event processing fix

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/de/settings.json, public/locales/en/settings.json, public/locales/fr/settings.json, public/locales/hi/settings.json, public/locales/id/settings.json, public/locales/ja/settings.json, public/locales/ko/settings.json, public/locales/pl/settings.json, public/locales/ru/settings.json, public/locales/tr/settings.json, src-tauri/src/configs/trait_config.rs, src-tauri/src/events.rs, src-tauri/src/events_emitter.rs, src-tauri/src/events_manager.rs, src-tauri/src/node_manager.rs, src-tauri/src/setup/phase_node.rs, src-tauri/src/setup/setup_manager.rs, src/containers/floating/Settings/sections/connections/ConnectionsSettings.tsx, src/containers/floating/Settings/sections/connections/Node.tsx, src/hooks/app/useTauriEventsListener.ts, src/store/useNodeStore.ts, src/types/backend-state.ts, src/types/events-payloads.ts
Minotari Node Debug section in the Connection Settings:
=> chore(quick load): node debug info in settings

public/locales/af/wallet.json, public/locales/cn/wallet.json, public/locales/de/wallet.json, public/locales/en/wallet.json, public/locales/fr/wallet.json, public/locales/hi/wallet.json, public/locales/id/wallet.json, public/locales/ja/wallet.json, public/locales/ko/wallet.json, public/locales/pl/wallet.json, public/locales/ru/wallet.json, public/locales/tr/wallet.json, src-tauri/src/commands.rs, src-tauri/src/main.rs, src/components/transactions/send/Send.tsx, src/types/invoke.d.ts
=> chore(send): amount validation

src-tauri/src/node/node_adapter.rs, src-tauri/src/node/node_manager.rs, src-tauri/src/progress_tracker_old.rs, src/containers/navigation/components/Wallet/SyncTooltip/styles.ts
* remove unused logs
Fix z-index of paper-wallet after merging with main
=> feat(quick load): fix paper wallet menu UI

public/locales/af/wallet.json, public/locales/cn/wallet.json, public/locales/de/wallet.json, public/locales/en/wallet.json, public/locales/fr/wallet.json, public/locales/hi/wallet.json, public/locales/id/wallet.json, public/locales/ja/wallet.json, public/locales/ko/wallet.json, public/locales/pl/wallet.json, public/locales/ru/wallet.json, public/locales/tr/wallet.json, src-tauri/src/events_manager.rs, src-tauri/src/events_service.rs, src/components/transactions/history/HistoryList.tsx, src/containers/navigation/components/Wallet/WalletBalanceMarkup.tsx, src/hooks/app/useTauriEventsListener.ts
Don't display any of the following until wallet scanning is finished:
* hide/show balance button
* tx history
* wallet balance
Instead, display info: "Wallet is scanning".
Unify balance/transactions updates.
* Gently wait when node takes it's time to start
Video demonstrating wallet syncing update:
https://github.com/user-attachments/assets/5089ae2e-011b-44cf-9337-94ce56bcb4f8
=> fix: wallet syncing problems

src-tauri/src/commands.rs, src-tauri/src/configs/trait_config.rs, src/containers/floating/Settings/sections/experimental/MonerodMarkup/MonerodMarkup.tsx, src/containers/floating/Settings/sections/experimental/P2poolMarkup.tsx, src/containers/floating/Settings/sections/experimental/TorMarkup/TorMarkup.tsx, src/containers/floating/Settings/sections/p2p/P2pMarkup.tsx
* Apply settings changes directly, without displaying restart modal
* Adjust titles etc to these changes
https://github.com/user-attachments/assets/42556154-438a-4baf-8a3a-f8c33fd40e43
=> fix(quick load): apply settings changes directly

src-tauri/src/telemetry_manager.rs
=> fix: fix cpu_usage in telemetry

public/locales/en/setup-progresses.json, src-tauri/src/events.rs, src-tauri/src/events_emitter.rs, src-tauri/src/events_manager.rs, src-tauri/src/setup/phase_core.rs, src-tauri/src/setup/phase_hardware.rs, src-tauri/src/setup/phase_node.rs, src-tauri/src/setup/phase_unknown.rs, src-tauri/src/setup/phase_wallet.rs, src-tauri/src/setup/setup_manager.rs, src/containers/floating/CriticalProblemDialog/CriticalProblemDialog.tsx
=> feat: [ quick load ] error dialog

src-tauri/src/mm_proxy_manager.rs
=> feat(quick load): wait more time for mmproxy ready

src-tauri/src/cpu_miner.rs, src-tauri/src/gpu_miner.rs, src-tauri/src/main.rs, src-tauri/src/node/node_adapter.rs, src-tauri/src/node/node_manager.rs, src-tauri/src/telemetry_manager.rs
broadcast only current node status
=> feat(quick load): separate and forward node status

docs/tauri_config/tauri_config.md, src-tauri/tauri.conf.json
Description
---
- sdded Google profile picture domain to CSP configuration
- updated the `tauri_config.md` docs
---
- #1831
=> fix(ui): add google profile img to csp

src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json
chore: version bump glytex to 0.2.21
=> chore: version bump glytex to 0.2.21

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/tauri.conf.json
=> chore(release): version 0.9.849

CHANGELOG.md
=> chore: release notes 0.9.849

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries_versions_esmeralda.json, src-tauri/binaries_versions_nextnet.json, src-tauri/src/internal_wallet.rs, src-tauri/src/wallet_adapter.rs, src-tauri/tauri.conf.json
=> chore(release): version 0.9.907

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
=> chore(release): version 0.9.909

src/components/transactions/history/ListItem.styles.ts, src/components/transactions/history/ListItem.tsx
=> fix(ui): adjust alignment on new chip so it appears centered

package-lock.json, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/binaries-versions/binaries_versions_nextnet.json, src-tauri/src/binaries/adapter_tor.rs, src-tauri/src/node/local_node_adapter.rs, src-tauri/src/node/node_adapter.rs, src-tauri/src/node/remote_node_adapter.rs, src-tauri/src/process_adapter.rs, src-tauri/src/process_watcher.rs, src-tauri/src/spend_wallet_adapter.rs, src-tauri/src/tor_adapter.rs, src-tauri/tauri.conf.json, src/components/transactions/history/ExpandedItem.tsx
=> chore(release): version 0.9.913

CHANGELOG.md
=> chore: release notes 0.9.914

src-tauri/src/websocket_events_manager.rs
Description
---
Fix mainnet string
---
---
---
---
=> fix: mainnet string for status

.github/workflows/ci.yml, .github/workflows/release.yml, src-tauri/Cargo.toml, src-tauri/src/app_in_memory_config.rs, src-tauri/src/telemetry_manager.rs, src-tauri/src/telemetry_service.rs
Description
---
Add `EXCHANGE_ID` to telemetry if feature `exchange-env` is enabled.
=> feat: add exchange id infro to telemetry

.github/workflows/release-exchange.yml
-fix secrets vulnerability in release-exchange workflow
=> fix: [ exchange miner ] secrets exposure

src/components/exchanges/display/WalletDisplay.tsx, src/store/actions/walletStoreActions.ts
Description
---
- fixed borked check
=> fix(ui): [exchange miner] incorrect check 

.github/workflows/release-exchange.yml, exchanges.json
Once merged replace secret **EXCHANGES_ESCAPED_JSON**
with stringified json structure like this one:
```
{
"exchanges": [
{
"id": "TXC",
"secret_name": "Binance"
}
]
}
```
In my case for testing it resolved to `EXCHANGES_ESCAPED_JSON = "{\n    \"exchanges\": [\n        {\n            \"id\": \"TXC\",\n            \"secret_name\": \"Binance\"\n        }\n    ]\n}"`
=> feat: exchange miner remove json file

.github/workflows/release-exchange.yml, exchanges.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/credential_manager.rs, src-tauri/src/main.rs
- Updated APPLICATION_FOLDER_ID to take into account exchange miner ids
- Updated main binary and product name to include exchange miner name
=> fix: exchange miner application id and name

src-tauri/src/commands.rs, src/components/exchanges/connect/Connect.tsx, src/hooks/app/useTauriEventsListener.ts
Description
---
Await emitting wallet changed events.
=> fix(exchange-miner): init address from modal

src-tauri/src/commands.rs, src-tauri/src/setup/setup_manager.rs
- Adjustments to phase shutdowns / restarts in `set_tari_address`
=> fix: exchange miner shutdown wallet phase

src/hooks/app/useDisableRefresh.ts
Description
---
- add check for inputs or textareas in `useDisableRefresh` 
---
- https://github.com/tari-project/universe/issues/2145
---
- lovally (removed the dev env check:D)
=> fix(ui): allow contextmenu on inputs/textareas

src/components/exchanges/display/WalletDisplay.tsx, src/components/exchanges/display/wallet.styles.ts, src/components/transactions/receive/Address.style.ts, src/theme/palettes/dark.ts
Description
---
- fix styling for truncated address in light mode
=> fix(ui): light mode address styling

src-tauri/src/configs/config_mining.rs
Description
---
fix addresses per network
=> fix: pool addresses per network

CHANGELOG.md
=> chore: release notes for 1.1.1

src-tauri/src/pool_status_watcher.rs
=> fix: integer overflow in pool status data

CHANGELOG.md
=> chore: release notes 1.2.0

CHANGELOG.md
=> Release notes 1.2.0

eslint.config.js, src/App/sentryIgnore.ts, src/containers/floating/FloatingElements.tsx, src/hooks/airdrop/ws/useHandleWsGlobalEvent.ts, src/hooks/airdrop/ws/useHandleWsUserIdEvent.ts, src/hooks/app/useProgressEventsListener.ts, src/hooks/app/useTauriEventsListener.ts, src/hooks/swap/useWagmiAdapter.ts, src/i18initializer.ts, src/store/actions/walletStoreActions.ts, src/store/useBlockchainVisualisationStore.ts, src/utils/shared-logger.ts, src/utils/socket.ts
Description
---
just clean up some FE logs by logging less + adding a bit less info if not needed
=> chore: clean up FE log bloat

src/utils/formatters.ts
=> fix: formatting for zero

.github/workflows/release-exchange.yml, scripts/create-latest-json.sh
- [ Github flow ] Fixed dmg artifact upload
- [ Github flow ] Added upload for deb artifact
- [ Github flow ] Comment out upload for rpm packages
=> fix: github upload exchange miner

src-tauri/src/utils/platform_utils.rs
Description
---
- fix missed old event handler call
=> fix: emit call

public/locales/af/setup-progresses.json, public/locales/cn/setup-progresses.json, public/locales/de/setup-progresses.json, public/locales/en/setup-progresses.json, public/locales/fr/setup-progresses.json, public/locales/hi/setup-progresses.json, public/locales/id/setup-progresses.json, public/locales/ja/setup-progresses.json, public/locales/ko/setup-progresses.json, public/locales/pl/setup-progresses.json, public/locales/ru/setup-progresses.json, public/locales/tr/setup-progresses.json
Description
---
- adds missing translation key
=> chore: add bridge setup title

src-tauri/src/events_manager.rs, src-tauri/src/setup/phase_core.rs, src-tauri/src/utils/platform_utils.rs
Description
---
checked `initialize_preqesities` calls for each `cfg` type
=> fix: clippy for platform_utils

README.md
=> feat: add info on linting to the readme

src/components/transactions/receive/AddressQRCode.tsx, src/containers/floating/PaperWalletModal/sections/QRCodeSection/QRCodeSection.tsx
Description
---
bump QR code error correction (highest on receive QR with the logo)
=> fix(ui): bump QR code error correction

CHANGELOG.md
=> chore: release notes 1.2.2

src-tauri/src/app_in_memory_config.rs, src-tauri/src/main.rs
Description
---
Omit fetching exchange miner list if `EXCHANGE_ID` is `classic`
=> fix: omit exchange miner list fetching on classic mode

CHANGELOG.md
=> chore: release notes 1.2.6

CHANGELOG.md
=> chore: release notes 1.2.7

src-tauri/src/commands.rs, src/components/exchanges/universal/option/XCOption.tsx, src/components/wallet/components/details/styles.ts, src/containers/navigation/Sidebars/sections/Wallet.tsx
Description
---
Seedless UI flag was set twice while confirming exchange miner address
=> fix(exchange miner): seedless UI flag

src-tauri/src/auto_launcher.rs, src-tauri/src/binaries/binaries_manager.rs, src-tauri/src/cpu_miner.rs, src-tauri/src/github/cache.rs, src-tauri/src/tapplets/tapplets_manager.rs, src-tauri/src/wallet_manager.rs, src/components/exchanges/commonStyles.ts, src/components/transactions/wallet/Exchanges/styles.ts
Description
---
- remove border on button icons
- remove max width on modal icons
=> fix(ui): external link modal | adjust styling for full icons

src-tauri/src/events_emitter.rs, src/components/transactions/wallet/Exchanges/logos/Logos.tsx, src/components/wallet/seedwords/SeedWords.tsx, src/components/wallet/seedwords/components/Display.tsx, src/containers/floating/ResumeApplicationModal/ResumeApplicationModal.tsx, src/containers/floating/Settings/sections/wallet/MoneroAddressMarkup/MoneroAddressMarkup.tsx
Description
---
- emit wallet config payload as just `payload`
- fix seed word display loader state
- fix `src` error for tari logo
=> fix(ui): toggle loader + monero settings

src/components/exchanges/commonStyles.ts, src/components/exchanges/universal/exchangeAddress/styles.ts, src/components/exchanges/universal/option/XCOption.tsx, src/components/exchanges/universal/option/styles.ts, src/components/wallet/seedwords/EmptySeedWords.tsx, src/components/wallet/seedwords/components/Edit.tsx, src/components/wallet/seedwords/components/edit.styles.ts, src/hooks/app/useTauriEventsListener.ts, src/store/actions/walletStoreActions.ts
Description
---
- fix import seed words loading state on modal
- fix universal modal after switch back to tari
- remove restart messaging
- smol styling cleanups on modal
=> fix(ui): cleanups

src/containers/floating/EXModal/components/content.styles.ts
Description
---
- just fixes the longer logo img constraints
- tested locally, pics shared internally
=> fix: long logo overflow

src/components/exchanges/universal/option/XCOption.tsx, src/components/exchanges/universal/option/styles.ts, src/containers/floating/EXModal/components/content.styles.ts, src/types/exchange.ts
Description
---
- add field check for address help url
- made it a clickable button
- spacing adjustments
---
- tested locally
=> fix(ui): address help URL

src/components/exchanges/universal/option/XCOption.tsx
Description
---
Show the current mining address in the changer.
---
Just because you kind of expect it
---
Manually
=> feat: show current address in exchange changer

src/assets/icons/menu-dots.tsx, src/components/wallet/components/details/WalletDetails.tsx, src/components/wallet/components/details/actions/WalletCardActions.tsx, src/components/wallet/components/details/styles.ts, src/containers/navigation/components/Wallet/NumbersLoadingAnimation/styles.ts
- remove action menu
- remove "Mining here" pill
- skeleton loader style change
=> fix(ui): wallet ui tweaks

CHANGELOG.md
=> chore: release notes 1.2.10

src/components/exchanges/universal/option/XCOption.tsx
Description
---
- import `open` from `tauri`
=> fix(ui): help link

src/components/exchanges/universal/option/XCOption.tsx
Description
---
- fix check for build
---
- locally & `tsc`'d
=> fix(ui):  url check

src/components/transactions/history/List.tsx, src/store/actions/walletStoreActions.ts, src/store/useBlockchainVisualisationStore.ts
Instead of fetching bridge transactions every block we are checking if there is new transaction with dest address as cold wallet and checking if its missing in current bridge transaction list
=> fix: reduce bridge api requests

CHANGELOG.md
=> chore: release notes 1.2.14

src/components/elements/inputs/Select.styles.ts, src/components/elements/inputs/Select.tsx, src/components/transactions/history/FilterSelect.tsx, src/components/transactions/history/List.styles.ts, src/components/wallet/components/loaders/SyncLoading/SyncCountdown.tsx
- use short text for "Calculating time..."
- Adjust alignment of the list filter dropdown
=> fix(ui): sidebar ui adjustments

CHANGELOG.md
=> fix: release notes

src/components/VideoStream/styles.ts, src/components/elements/inputs/Select.styles.ts, src/components/elements/inputs/Select.tsx, src/containers/main/MainView.tsx, src/containers/main/Sync/Sync.tsx, src/containers/main/Sync/actions/ModeSelection.tsx, src/containers/main/Sync/actions/actions.style.ts, src/containers/main/Sync/components/Progress.tsx, src/containers/main/Sync/components/SyncActionCard.tsx, src/containers/main/Sync/components/syncAction.style.ts, src/containers/main/Sync/sync.styles.ts, src/containers/navigation/components/Miner/components/ModeSelect.tsx
Some cleanups for the initial Sync screen UI. 
- Better padding
- Consistant spacing
- Added subtle intro animation
- Fixed alignment and colors for the action buttons
- Light/Dark mode improvements
=> fix(ui): sync setup screen layout improvements

src-tauri/src/feedback.rs
Description
---
Fixes bug where not all log files were uploaded when submitted by user
Fixes #2463
---
---
In mainnet
---
Check the submitted logs from TU 
---
=> fix: not all log files being sent to server

CHANGELOG.md
=> chore: release notes 1.2.17

src-tauri/binaries-versions/binaries_versions_testnets.json, src-tauri/src/configs/config_core.rs, src-tauri/src/node/local_node_adapter.rs, src-tauri/src/node/node_adapter.rs, src-tauri/src/node/node_manager.rs, src-tauri/src/node/remote_node_adapter.rs, src-tauri/src/p2pool_manager.rs, src-tauri/src/spend_wallet_adapter.rs, src-tauri/src/spend_wallet_manager.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs
Description
---
Add support for http wallet scanning from the local base node.
---
Mo faster scanning
---
Locally
---
run the app
---
=> feat: http wallet support

public/locales/af/settings.json, public/locales/cn/settings.json, public/locales/de/settings.json, public/locales/en/settings.json, public/locales/fr/settings.json, public/locales/hi/settings.json, public/locales/id/settings.json, public/locales/ja/settings.json, public/locales/ko/settings.json, public/locales/pl/settings.json, public/locales/ru/settings.json, public/locales/tr/settings.json, src-tauri/src/commands.rs, src-tauri/src/configs/config_ui.rs, src-tauri/src/configs/config_wallet.rs, src-tauri/src/credential_manager.rs, src-tauri/src/internal_wallet.rs, src-tauri/src/main.rs, src-tauri/src/setup/phase_wallet.rs, src/store/actions/walletStoreActions.ts
Description
---
* Add functionality to remove tari/monero wallets(from credentials)
* Reset settings clears wallets` credentials
* Refactor ConfigWallet setters
* Make wallet_id case sensitive
=> fix: reset settings removes wallets

src/store/actions/miningMetricsStoreActions.ts
- Removed debugging line which was overriding setup manager flow for unlocking parts of the app
=> fix: remote node landing on main view to quickly

src-tauri/src/node/local_node_adapter.rs, src-tauri/src/node/node_adapter.rs, src-tauri/src/node/node_manager.rs, src-tauri/src/node/remote_node_adapter.rs, src-tauri/src/spend_wallet_adapter.rs, src-tauri/src/spend_wallet_manager.rs, src-tauri/src/wallet_adapter.rs, src-tauri/src/wallet_manager.rs
Description
---
* Use only node's http url for spend and view wallets
=> fix: use only node http url for wallet

src/containers/floating/Settings/sections/connections/ConnectionsSettings.tsx
Description
---
- just removed the check for dev so the dropdown is available in all envs
=> chore(ui): remove development check for node type settings dropdown

CHANGELOG.md
=> chore: release notes 1.5.3

CHANGELOG.md
=> fix: release notes 1.5.3

package-lock.json, src/components/AdminUI/groups/DialogsGroup.tsx, src/components/exchanges/connect/Connect.tsx, src/components/wallet/sidebarWallet/SidebarWallet.tsx, src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/WalletAddressMarkup.tsx, src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/index.ts, src/containers/floating/Settings/sections/wallet/WalletSettings.tsx, src/containers/floating/Settings/sections/wallet/components/AddressEditor.tsx, src/containers/floating/Settings/sections/wallet/styles.ts, src/store/actions/appConfigStoreActions.ts, src/store/actions/bridgeApiActions.ts, src/store/actions/walletStoreActions.ts, src/store/useWalletStore.ts
Description
---
- fix wallet store values being overwritten
- add display (for now) area for ETH Address in Wallet Settings
- wallet settings styling tweaks
=> feat: view address | validation check fixes [overall still wip]

src/containers/floating/Settings/sections/wallet/PinMarkup.tsx, src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/BaseAddress.tsx, src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/ETHAddress.tsx, src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/EmojiAddress.tsx, src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/WalletAddressMarkup.tsx, src/containers/floating/Settings/sections/wallet/WalletAddressMarkup/styles.ts, src/containers/floating/Settings/sections/wallet/WalletSettings.tsx, src/containers/floating/Settings/sections/wallet/components/AddressEditor.tsx, src/containers/floating/Settings/sections/wallet/styles.ts
Description
---
mostly wallet settings changes: 
- split out different address types into their own components
- allow for editing of ETH address (and then re-generating Tari Address)
=> feat: edit eth address

src/hooks/exchanges/fetchExchanges.ts
Description
---
- just adds the `wXTM` query param for filtering 
| without param |
| :---: |
| <img width="1256" height="772" alt="Screenshot 2025-08-01 at 15 12 28" src="https://github.com/user-attachments/assets/95c473f3-8668-4ea3-a0d4-db53b4483253" /> |
| with param |
| :---: |
| <img width="1325" height="888" alt="Screenshot 2025-08-01 at 15 11 34" src="https://github.com/user-attachments/assets/044f538a-f6e4-47ef-bfdd-f5abb2142958" /> |
| without param + new NON wXTM  |
| :---: |
| <img width="1256" height="772" alt="Screenshot 2025-08-01 at 15 16 17" src="https://github.com/user-attachments/assets/b8a30f49-dce5-4adf-a2e4-70f0be923451" /> |
| with param + new NON wXTM  |
| :---: |
| <img width="1360" height="810" alt="Screenshot 2025-08-01 at 15 16 42" …
=> chore(ui): add wXTM param

src/hooks/exchanges/fetchExchangeContent.ts
Description
---
- use `handleAirdropRequest` here too for admin
=> fix: use rwa specific request for individual items too

CHANGELOG.md
=> chore: release notes 1.5.4

src/hooks/airdrop/utils/useAvatarGradient.ts
Just a quick fix for the avatar image not showing, this was borked in the react compiler update. 
Note: In a future update ill make a better Avatar component instead of using this hook approach.
=> fix(ui): fix avatar image not showing

CHANGELOG.md
=> chore: release notes 1.5.7

src-tauri/src/network_utils.rs, src-tauri/src/requests/mod.rs, src/hooks/airdrop/stateHelpers/useAirdropTokensRefresh.ts, src/hooks/airdrop/utils/useHandleRequest.ts, src/hooks/mining/useFetchExplorerData.ts, src/hooks/mining/useMinerCount.ts, src/utils/index.ts
This pull request introduces a new utility, `defaultHeaders`, and applies it across multiple API requests to standardize request headers throughout the codebase. This change improves consistency, makes it easier to update headers in the future, and ensures that all relevant requests include the custom `X-Requested-With` header for identification.
**Header standardization and utility introduction:**
* Added the `defaultHeaders` export to `src/utils/index.ts`, which sets a custom `X-Requested-With` header using the app version from environment variables.
**Refactoring API requests to use the new utility:**
* Updated `fetchExplorerData` in `src/hooks/mining/useFetchExplorerData.ts` to include `defaultHeaders` in the fetch request headers.
* Updated `fetchMinerStats` in …
=> feat: add X-Requested-With header

.updater/alpha-latest.json, .updater/latest.json
=> chore(auto-update): to version 1.5.9

.updater/alpha-latest.json, .updater/latest.json
=> chore(auto-update): to 1.5.12

src-tauri/src/binaries/binaries_manager.rs, src-tauri/src/binaries/mod.rs, src-tauri/src/binaries/windows_defender.rs
=> fix: missing windows no window flag on defender scripts

.updater/alpha-latest.json, .updater/beta-latest.json, .updater/latest.json
=> chore(auto-update): to version 1.5.14

src-tauri/src/setup/phase_node.rs
shutdown signal was for node phase, but task was under common phase
=> fix: closing issue

CHANGELOG.md
=> chore: release notes 1.5.17

.github/workflows/audit.yml
Description
Add an npm audit workflow
Check for security issues
Runs in local fork
=> chore(ci): add an audit workflow

src-tauri/src/mining/pools/gpu_pool_manager.rs
=> fix: ensure pool is turned off when fallbacking to glytex

src/containers/floating/Settings/components/LanguageDropdown.tsx
=> fix: language drop down selection not updating

src-tauri/src/binaries/binaries_manager.rs
- Possible fix for `Operation did not complete successfully because the file contains a virus or potentially unwanted software. (os error 225)` during downloading
=> fix: add exclusion for binaries to windows defender before we download them

src/components/exchanges/universal/exchangeAddress/ExchangeAddress.tsx, src/components/exchanges/universal/option/XCOption.tsx, src/types/invoke.d.ts
=> fix: exchange address input not registering change

CHANGELOG.md
=> chore: release v1.6.2: The Luminous Threshold

src-tauri/src/commands.rs, src/containers/floating/Settings/sections/pools/CpuPoolsSettings.tsx, src/containers/floating/Settings/sections/pools/GpuPoolsSettings.tsx, src/store/actions/appConfigStoreActions.ts, src/types/invoke.d.ts
- Fixed errors related to updating pools config
=> fix: updating pool config

src-tauri/src/mining/cpu/manager.rs
Description
---
When running on eco, set xmrig to light mode and save 2GB of memory.
---
Lower resource utilization when running on eco.
=> feat: xmrig in light mode
